"""Generate YC config from data/yc-companies.json (built by build_yc_companies.py).

Writes:
  * yc.yaml            — YC-only config (hiring companies, for quick YC runs)
  * companies.yaml     — appends the same ``yc:`` list so the daily run includes it

Only companies currently marked as hiring are configured; re-run the build +
generator whenever you want to refresh the list.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "yc-companies.json"
YC_YAML = ROOT / "yc.yaml"
COMPANIES_YAML = ROOT / "companies.yaml"


def main() -> int:
    companies = json.loads(DATA.read_text(encoding="utf-8"))
    hiring = sorted(c["slug"] for c in companies if c.get("isHiring"))
    if not hiring:
        print("no hiring companies found; run scripts/build_yc_companies.py first")
        return 1

    def yaml_item(slug: str) -> str:
        # Quote slugs that would parse as numbers (e.g. "222") in YAML.
        return f'  - "{slug}"' if slug.isdigit() else f"  - {slug}"

    yc_list = "\n".join(yaml_item(slug) for slug in hiring)

    # yc.yaml — standalone YC-only config.
    header = """# YC-funded startups — generated by scripts/generate_yc_config.py.
# Source: ycombinator.com/companies/<slug> (server-rendered, keyless).
# Only companies currently hiring are listed ({n}).
boards: []
rss_feeds: []
greenhouse: []
ashby: []
bamboohr: []
lever: []
workday: []
tcs: []
smartrecruiters: []
workable: []
breezy: []
teamtailor: []
hirehive: []
recruitee: []
rise: []
adzuna: []
usajobs: []
jobvite: []
icims: []
yc:
{yc_list}
companies: []
""".format(n=len(hiring), yc_list=yc_list)
    YC_YAML.write_text(header, encoding="utf-8")

    # companies.yaml — rewrite the region between `icims:` and `api_keys:` with
    # the icims list followed by the generated yc list (idempotent).
    lines = COMPANIES_YAML.read_text(encoding="utf-8").splitlines(keepends=True)
    i_icims = next((i for i, l in enumerate(lines) if l.startswith("icims:")), -1)
    i_api = next((i for i, l in enumerate(lines) if l.startswith("api_keys:")), -1)
    if i_icims < 0 or i_api < 0:
        print("could not find icims:/api_keys: markers in companies.yaml", file=__import__("sys").stderr)
        return 1
    clean = [
        "icims:\n",
        "  - here\n  - rambus\n  - swift\n",
        "# YC-funded startups (ycombinator.com/companies/<slug>, server-rendered).\n",
        "# Generated by scripts/generate_yc_config.py; hiring companies only.\n",
        "yc:\n",
        *(item + "\n" for item in yc_list.splitlines()),
    ]
    COMPANIES_YAML.write_text("".join(lines[:i_icims] + clean + lines[i_api:]), encoding="utf-8")

    print(f"yc.yaml: {len(hiring)} hiring companies")
    print(f"companies.yaml: yc section updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
