"""Turn data/top-1000-employers.csv into JobCollector company config.

Writes two things:

1. ``companies-top1000.yaml`` (project root) — a standalone, loadable config
   with ALL 1000 ranked employers. Companies whose website is known in the
   source data get a live entry with ``careers_url = https://<website>/careers``
   (a best-effort guess — most big employers use that path, but verify
   important ones). Companies without a website are emitted as commented-out
   "pending" entries ready to fill in.

2. ``companies-top1000.live.yaml`` — just the live entries (no ``companies:``
   key), for splicing into the main ``companies.yaml``.

The list is ranked by employee count — the standard proxy for hiring volume —
so the top of the file is exactly "the companies that hire the most".

Usage:
    python scripts/generate_companies_top1000.py            # write the YAML files
    python scripts/generate_companies_top1000.py --append   # ...and splice the live
                                                            # block into companies.yaml
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV = ROOT / "data" / "top-1000-employers.csv"
OUT = ROOT / "companies-top1000.yaml"
LIVE_OUT = ROOT / "companies-top1000.live.yaml"

# Markers delimiting the generated block inside companies.yaml.
APPEND_START = "# >>> TOP-1000 EMPLOYERS (generated by scripts/generate_companies_top1000.py)"
APPEND_END = "# <<< END TOP-1000 EMPLOYERS"

BANNER = """\
# =============================================================================
# Top-1000 employers, ranked by employee count (proxy for hiring volume).
# GENERATED by scripts/generate_companies_top1000.py — do not edit by hand.
# Regenerate any time with:  python scripts/generate_companies_top1000.py
#
# careers_url values are best-effort guesses (https://<website>/careers); most
# big employers use that path but not all (e.g. amazon.jobs). Verify the ones
# you care about. max_pages=20 keeps the bulk crawl bounded; raise it per
# company if a career site has more open roles than that.
# =============================================================================
"""


def registrable_domain(website: str) -> str:
    """Best-effort eTLD+1 so subdomain career sites are still followed
    (careers.walmart.com under www.walmart.com)."""
    host = website.strip().lower().split("/")[0].split(":")[0].strip(".")
    labels = [p for p in host.split(".") if p]
    if len(labels) <= 2:
        return host
    if len(labels[-1]) == 2 and labels[-2] in {
        "co", "com", "net", "org", "gov", "ac", "edu", "or", "ne",
    }:
        return ".".join(labels[-3:])
    return ".".join(labels[-2:])


def main() -> int:
    append = "--append" in sys.argv
    rows = []
    with open(CSV, encoding="utf-8") as f:
        for r in csv.DictReader(f):
            rows.append(r)
    if not rows:
        print(f"No rows in {CSV} — run scripts/build_top1000.py first.", file=sys.stderr)
        return 1

    live: list[str] = []
    pending: list[str] = []
    for r in rows:
        website = (r["website"] or "").strip()
        name = r["company"].strip()
        rank = r["rank"]
        if website:
            live.append(
                "  - name: \"{name}\"\n"
                "    careers_url: \"https://{website}/careers\"\n"
                "    domain: \"{domain}\"\n"
                "    max_pages: 20\n".format(
                    name=name.replace('"', "'"),
                    website=website,
                    domain=registrable_domain(website),
                )
            )
        else:
            pending.append(
                "  # rank {rank} · {name} ({src}) — no website in source data.\n"
                "  # - name: \"{name}\"\n"
                "  #   careers_url: \"https://REPLACE-WITH-REAL-CAREERS-URL\"\n"
                "  #   max_pages: 20\n".format(
                    rank=rank, name=name.replace('"', "'"), src=r["source"]
                )
            )

    with open(OUT, "w", encoding="utf-8") as f:
        f.write(BANNER)
        f.write("companies:\n")
        f.write("".join(live))
        f.write("".join(pending))
    print(f"wrote {OUT} ({len(live)} live + {len(pending)} pending entries)")

    with open(LIVE_OUT, "w", encoding="utf-8") as f:
        f.write("".join(live))
    print(f"wrote {LIVE_OUT} ({len(live)} entries)")

    if append:
        splice_into_main(live)
    return 0


def splice_into_main(live: list[str]) -> None:
    """Insert the live entries into companies.yaml under a banner, replacing any
    previously generated block so re-running is idempotent."""
    path = ROOT / "companies.yaml"
    text = path.read_text(encoding="utf-8")
    start = text.find(APPEND_START)
    end = text.find(APPEND_END)
    if start != -1 and end != -1 and end > start:
        text = text[:start] + text[end + len(APPEND_END):]
        print("replaced existing generated block in companies.yaml")
    block = (
        "\n" + APPEND_START + "\n"
        "# ~500 of the world's biggest employers by headcount (see\n"
        "# companies-top1000.yaml for the full 1000 incl. pending entries).\n"
        "# careers_url values are guesses (https://<website>/careers); verify.\n"
        + "".join(live)
        + APPEND_END + "\n"
    )
    # The generated entries continue the existing `companies:` list, which is the
    # last top-level key in the stock layout, so the block goes at the end of the
    # file. (If companies.yaml has keys after `companies:`, move the block.)
    if not text.endswith("\n"):
        text += "\n"
    text += "\n" + block + "\n"
    path.write_text(text, encoding="utf-8")
    print(f"spliced {len(live)} entries into {path.name}")


if __name__ == "__main__":
    sys.exit(main())
