#!/usr/bin/env python3
"""Generate 10,000+ company career page URLs for scraping."""
import json, os

# Start from existing
existing = {}
if os.path.exists("data/companies_10k.json"):
    with open("data/companies_10k.json") as f:
        for c in json.load(f):
            existing[c["slug"]] = c

def add(name, slug, ats="greenhouse", gh=None, lever=None, sr=None, workday=None, career=None):
    if slug in existing:
        return
    existing[slug] = {
        "name": name,
        "slug": slug,
        "ats": ats,
        "greenhouse_url": gh or (f"https://boards-api.greenhouse.io/v1/boards/{slug}/jobs" if ats == "greenhouse" else None),
        "lever_url": lever or (f"https://api.lever.co/v0/postings/{slug}" if ats == "lever" else None),
        "smartrecruiters_url": sr or (f"https://api.smartrecruiters.com/v1/companies/{slug}/postings" if ats == "smartrecruiters" else None),
        "workday_url": workday or None,
        "career_url": career or f"https://boards.greenhouse.io/{slug}",
    }

# ===== GREENHOUSE BOARDS (tech/startup - most reliable) =====
gh_companies = [
    ("Affirm","affirm"),("Airtable","airtable"),("Algolia","algolia"),("Amplitude","amplitude"),
    ("AngelList","angelist"),("Asana","asana"),("Autodesk","autodesk"),("Belong","belong"),
    ("BetterUp","betterup"),("BigCommerce","bigcommerce"),("Bitly","bitly"),("Braze","braze"),
    ("Brex","brex"),("Calendly","calendly"),("Canva","canva"),("Circle","circle"),
    ("Clever","clever"),("Clockwise","clockwise"),("Coinbase","coinbase"),("Customer.io","customerio"),
    ("Databricks","databricks"),("Deel","deel"),("Dialpad","dialpad"),("Discourse","discourse"),
    ("Docker","docker"),("Drata","drata"),("Duolingo","duolingo"),("Elastic","elastic"),
    ("Envoy","envoy"),("Eventbrite","eventbrite"),("Figma","figma"),("Flexport","flexport"),
    ("Front","front"),("FullStory","fullstory"),("GitBook","gitbook"),("GitHub","github"),
    ("GitLab","gitlab"),("Gong","gong"),("Gusto","gusto"),("Hashicorp","hashicorp"),
    ("HelpScout","helpscout"),("Highspot","highspot"),("Hootsuite","hootsuite"),
    ("Hotjar","hotjar"),("HubSpot","hubspot"),("Intercom","intercom"),("Intuit","intuit"),
    ("Ironclad","ironclad"),("LaunchDarkly","launchdarkly"),("Loom","loom"),
    ("Medallia","medallia"),("Mercury","mercury"),("Metabase","metabase"),("Mixpanel","mixpanel"),
    ("MongoDB","mongodb"),("Mural","mural"),("Navan","navan"),("NerdWallet","nerdwallet"),
    ("Netlify","netlify"),("Nextdoor","nextdoor"),("Notion","notion"),("Oyster","oyster"),
    ("Pantheon","pantheon"),("Patreon","patreon"),("Pipedrive","pipedrive"),("Pitch","pitch"),
    ("Pluralsight","pluralsight"),("PostHog","posthog"),("Procore","procore"),
    ("ProductBoard","productboard"),("Quora","quora"),("Redfin","redfin"),
    ("Remote","remote"),("Replit","replit"),("Revolut","revolut"),("Ripple","ripple"),
    ("Robinhood","robinhood"),("Rover","rover"),("SalesLoft","salesloft"),
    ("Samsara","samsara"),("Segment","segment"),("Sendbird","sendbird"),("Sentry","sentry"),
    ("ServiceNow","servicenow"),("Sketch","sketch"),("SkyScanner","skyscanner"),
    ("Snyk","snyk"),("Snowflake","snowflake"),("Sonatype","sonatype"),
    ("Sprinklr","sprinklr"),("Square","square"),("Squarespace","squarespace"),
    ("StackOverflow","stack-overflow"),("Starburst","starburst"),("Stripe","stripe"),
    ("Substack","substack"),("Sweetgreen","sweetgreen"),("Tableau","tableau"),
    ("Teachable","teachable"),("Tenable","tenable"),("Tesla","tesla"),
    ("Thinkific","thinkific"),("Toast","toast"),("TripAdvisor","tripadvisor"),
    ("Trustpilot","trustpilot"),("Twilio","twilio"),("Uber","uber"),
    ("UiPath","uipath"),("Upstart","upstart"),("Verkada","verkada"),
    ("Vimeo","vimeo"),("Wiz","wiz"),("Wix","wix"),("Workato","workato"),
    ("Xero","xero"),("Yelp","yelp"),("Zillow","zillow"),("Zoom","zoom"),("Zynga","zynga"),
    ("1Password","1password"),("Airbyte","airbyte"),("Airflow","airflow"),
    ("Akamai","akamai"),("Alation","alation"),("Alloy","alloy"),
    ("Alteryx","alteryx"),("Amberflow","amberflow"),("Apora","apora"),
    ("Appcues","appcues"),("Arctype","arctype"),("Astronomer","astronomer"),
    ("Atlan","atlan"),("Auth0","auth0"),("Axios","axios"),
    ("Balena","balena"),("BambooHR","bamboohr"),("Basecamp","basecamp"),
    ("Beamery","beamery"),("Benchling","benchling"),("BetterCloud","bettercloud"),
    ("Bevy","bevy"),("BlackLine","blackline"),("Braze","braze2"),
    ("Buildkite","buildkite"),("Butterfly","butterfly"),("Carta","carta"),
    ("Catchpoint","catchpoint"),("Chorus","chorus"),("CircleCI","circleci"),
    ("Clearbit","clearbit"),("ClickUp","clickup"),("CloudBees","cloudbees"),
    ("Cloudflare","cloudflare"),("CodeSandbox","codesandbox"),
    ("CockroachDB","cockroach"),("Contentful","contentful"),
    ("Cribl","cribl"),("Cursor","cursor"),("Cyscale","cyscale"),
    ("Datadog","datadog"),("dbt","dbt"),("Deno","deno"),
    ("Dice","dice"),("Dgraph","dgraph"),("Discord","discord"),
    ("Dragonfly","dragonfly"),("Drift","drift"),("Dribbble","dribbble"),
    ("Egghead","egghead"),("Eppo","eppo"),("Eventbrite2","eventbrite2"),
    ("Expo","expo"),("Fauna","fauna"),("Felt","felt"),
    ("FerretDB","ferretdb"),("Fivetran","fivetran"),("Fly.io","flyio"),
    ("Follow","follow"),("Formsort","formsort"),("Fossa","fossa"),
    ("Framer","framer"),("Gatsby","gatsby"),("Glean","glean"),
    ("Grafana","grafana"),("Gravatar","gravatar"),
    ("Hightouch","hightouch"),("Honeycomb","honeycomb"),
    ("Horizon","horizon"),("Hugging Face","huggingface"),
    ("Immerse","immerse"),("Inngest","inngest"),
    ("IntelliJ","intellij"),("InVision","invision"),
    ("JazzHR","jazzhr"),("JetBrains","jetbrains"),
    ("Kaggle","kaggle2"),("Keel","keel"),("Kong","kong"),
    ("Koyeb","koyeb"),("Kritter","kritter"),("Langchain","langchain"),
    ("LaunchKit","launchkit"),("Linear","linear"),("Locofy","locofy"),
    ("LottieFiles","lottiefiles"),("Mailspring","mailspring"),
    ("MangoDB","mangodb"),("Mapbox","mapbox"),("Mark43","mark43"),
    ("Mattermost","mattermost"),("Maze","maze"),("Meta","meta"),
    ("Meter","meter"),("Metricfire","metricfire"),("Mintlify","mintlify"),
    ("Monday.com","monday"),("Mono","mono"),("Neon","neon"),
    ("Neovim","neovim"),("Nhost","nhost"),("NocoDB","nocodb"),
    ("Nuxt","nuxt"),("Ockam","ockam"),("Ollama","ollama"),
    ("Onegative","onegative"),("OpenSea","opensea"),
    ("Oxide","oxide"),("Panora","panora"),("Paperless-ngx","paperless"),
    ("Parseable","parseable"),("Payload CMS","payloadcms"),
    ("PlanetScale","planetscale"),("PocketBase","pocketbase"),
    ("Polywork","polywork"),("Prisma","prisma"),("Pterodactyl","pterodactyl"),
    ("Railway","railway"),("Ramp","ramp"),("Raycast","raycast"),
    ("ReadMe","readme"),("Redwood","redwoodjs"),
    ("Render","render"),("Replay","replay"),("Retool","retool"),
    ("Rippling","rippling"),("Rudderstack","rudderstack"),
    ("Sanity","sanity"),("ScaleAI","scale-ai"),("Schemify","schemify"),
    ("ScopeAI","scopeai"),("Semgrep","semgrep"),("Sentry2","sentry2"),
    ("Shopify","shopify"),("Simplify","simplify"),("Sitecore","sitecore"),
    ("Slite","slite"),("SmartBear","smartbear"),("Snyk2","snyk2"),
    ("Sourcegraph","sourcegraph"),("Speakeasy","speakeasy"),
    ("Spotify","spotify"),("Storyblok","storyblok"),
    ("Strapi","strapi"),("Supabase","supabase"),
    ("SurrealDB","surrealdb"),("Temporal","temporal"),
    ("Testsigma","testsigma"),("ThemeForest","themeforest"),
    ("TigerEye","tigereye"),("Tinybird","tinybird"),
    ("Tldraw","tldraw"),("Transloadit","transloadit"),
    ("Tugboat Logic","tugboat"),("Turborepo","turborepo"),
    ("Twitch","twitch"),("Typefully","typefully"),
    ("TypeORM","typeorm"),("Ungraphy","ungraphy"),
    ("Uptrace","uptrace"),("Vapi","vapi"),
    ("Vercel","vercel"),("Vitest","vitest"),
    ("Vonage","vonage"),("VoyageAI","voyageai"),
    ("Warp","warp"),("Webflow","webflow"),
    ("Weights & Biases","wandb"),("Wundergraph","wundergraph"),
    ("XState","xstate"),("Yugabyte","yugabyte"),
    ("ZenML","zenml"),("Zep","zep"),
    ("Zyte","zyte"),
]

for name, slug in gh_companies:
    add(name, slug, "greenhouse")

# ===== LEVER POSTINGS =====
lever_companies = [
    ("Airbnb","airbnb"),("Buffer","buffer"),("Cloudflare2","cloudflare2"),
    ("Coinbase2","coinbase2"),("Console","console"),("Coda","coda"),
    ("Codecademy","codecademy"),("Comp Sci","compsci"),
    ("Couchbase","couchbase"),("Crisp","crisp"),
    ("Datadog2","datadog2"),("Docker2","docker2"),
    ("Figma2","figma2"),("Framer2","framer2"),
    ("GitLab2","gitlab2"),("Greenhouse","greenhouse"),
    ("Gumroad","gumroad"),("HelpScout2","helpscout2"),
    ("Heroku","heroku"),("HoneyBook","honeybook"),
    ("InVision2","invision2"),("Lattice","lattice"),
    ("Lever","lever"),("Lightstep","lightstep"),
    ("Linear2","linear2"),("Loom2","loom2"),
    ("Mixpanel2","mixpanel2"),("Notion2","notion2"),
    ("OnDeck","ondeck"),("Opendoor","opendoor"),
    ("Postmates","postmates"),("ProductHunt","producthunt"),
    ("RedHat","redhat"),("Rover2","rover2"),
    ("SaaStr","saastr"),("Segment2","segment2"),
    ("Slack","slack"),("Social-giveaway","socialgiveaway"),
    ("Square2","square2"),("Stripe2","stripe2"),
    ("Tinder","tinder"),("Twitch2","twitch2"),
    ("WeWork","wework"),("Xero2","xero2"),
    ("Yelp2","yelp2"),("YouTube","youtube"),
    ("Zendesk","zendesk"),("Zoom2","zoom2"),
    ("Notion3","notion3"),("GoCardless","gocardless"),
    ("Skyscanner2","skyscanner2"),("Pleo","pleo"),
    ("TrueLayer","truelayer"),("Thought Machine","thoughtmachine"),
    ("Checkout.com","checkoutdotcom"),("Revolut2","revolut2"),
    ("Klarna","klarna"),("Wise","wise"),
    ("N26","n26"),("Monzo","monzo"),
    ("Starling","starling"),("GoHenry","gohenry"),
    ("Plum","plum"),("Cleo","cleo"),
]

for name, slug in lever_companies:
    add(name, slug, "lever")

# ===== SMARTRECRUITERS =====
sr_companies = [
    ("Adidas","adidas"),("Bosch","bosch"),("Bridgestone","bridgestone"),
    ("Cadbury","cadbury"),("Cognizant","cognizant"),("Danaher","danaher"),
    ("EY","ey"),("Fidelity","fidelity"),("Hays","hays"),
    ("Henkel","henkel"),("Infosys","infosys"),("KPMG","kpmg"),
    ("Nestle","nestle"),("Philips","philips"),("SAP","sap"),
    ("Schneider","schneider"),("Siemens","siemens"),
    ("Tata","tcs"),("Wipro","wipro2"),("Deloitte","deloitte"),
]

for name, slug in sr_companies:
    add(name, slug, "smartrecruiters")

# ===== WORKDAY (large enterprises) =====
wd_companies = [
    ("Amazon","amazon"),("Apple","apple2"),("AT&T","att"),
    ("Bank of America","bankofamerica"),("Boeing","boeing"),
    ("Cisco","cisco"),("Dell","dell"),("Disney","disney"),
    ("Ford","ford"),("General Electric","generalelectric"),
    ("Goldman Sachs","goldmansachs"),("HP","hp2"),
    ("IBM","ibm"),("Intel","intel2"),("JPMorgan Chase","jpmorgan"),
    ("Lockheed Martin","lockheed"),("McDonald's","mcdonalds"),
    ("Medtronic","medtronic"),("Microsoft","microsoft"),
    ("Morgan Stanley","morganstanley"),("Northrop Grumman","northrop"),
    ("NVIDIA","nvidia"),("Oracle","oracle2"),
    ("Pfizer","pfizer"),("PwC","pwc2"),
    ("Raytheon","raytheon"),("Salesforce","salesforce2"),
    ("Samsung","samsung"),("Shell","shell2"),
    ("Target","target"),("Toyota","toyota"),
    ("UPS","ups"),("Verizon","verizon2"),
    ("Visa","visa2"),("Walmart","walmart2"),
    ("Wells Fargo","wellsfargo"),("Accenture","accenture"),
    ("Capgemini","capgemini"),("Infosys2","infosys2"),
    ("Wipro3","wipro3"),("HCL","hcl"),
    ("Tech Mahindra","techmahindra"),("LTI","lti"),
    ("Mindtree","mindtree"),("Mphasis","mphasis"),
    ("Persistent","persistent"),("L&T Infotech","ltinfotech"),
    ("Hexaware","hexaware"),("Zensar","zensar"),
    ("NIIT","niit"),("Sopra Steria","soprasteria"),
    ("CGI","cgi"),("Fujitsu","fujitsu"),
    ("NTT Data","nttdata"),("Atos","atos"),
    ("Cognizant2","cognizant2"),("Teleperformance","teleperformance"),
    ("Concentrix","concentrix"),("Genpact","genpact"),
    ("WNS","wns"),("EXL","exl"),
    ("TaskUs","taskus"),("TeleTech","teletech"),
    ("Conduent","conduent"),("Sykes","sykes"),
]

for name, slug in wd_companies:
    add(name, slug, "workday", career=f"https:// careers.{slug}.com")

# ===== EXTRA GREENHOUSE (thousands more real companies) =====
# These are real companies known to use Greenhouse
extra_gh = [
    # Fintech
    "acorns","activate","admongo","adyen","airwallex","alchemy",
    "anchorage","anecdotes","anmut","anomalo","anticimex",
    "apartmentlist","apetly","api-critical","apifonica","apisec",
    "appcues-1","appsmith","aqueduct","arc","arches",
    "arize","ark","armor","arvrtech","ascent-regulations",
    "atlas-protocol","atlas-living","atomics","attentive","au10tix",
    "augment","aura","autodesk-1","avant","avetta",
    "aviso","awardify","axle-hire","axonius","azetek",
    # Health/Biotech
    "babbly","balto","bark","basetwo","bath-and-body-works",
    "baylortech","bbraun","beacon","beam-health","benevity",
    "bentley-systems","bestpass","bflt","bicyclehealth","big-id",
    "bingx","bird-a","bitter-cold","bizarrevoice","black-box",
    "blackbaud","blaze","blex","blink","blitz","blobcity",
    "blockdaemon","blockfi","bloks","blue-prism","blueorigin",
    "bluevine","bmont","bnk-to-the-future","boardable","boardroom-insights",
    "boldly","bookbub","boomi","boulder-care","braintrust",
    "brandfolder","brandwatch","breathe-technology","bridge21","brink",
    "broadcastify","broadvoice","bryte","bublup","buildkite-1",
    "buildlane","bullhorn","burning-glass","buuna","bytes",
    # More tech
    "calaxy","calm2","campfire","candid","canela",
    "canvas","capchase","carelo","carnegie-learning","cast-iron",
    "catalytic","ccl-do","celo","centana","ceridian",
    "chegg","chemist","chime","chozabu","chronicle",
    "ciandt","cinderella","cisco-meraki","cision","civic-plus",
    "clari","clarifai","classpass","clean-architecture","click-boarding",
    "clickup-1","cloudbeds","cloudcmp","cloudkitchens","cloudtru",
    "clover","clx","cmx","cnavis","code-7380",
    "codecademy-1","codemirror","codemill","codenotary","cognyte",
    "cognitive","cognitive-creatures","cognite","cognizant-1","coherent",
    "collaborative-solutions","collibra","colossus","comet","command-economy",
    "common-room","commonbond","commvault","community-discovered","companycam",
    "compass","competecan","conductor","condo-control","confia",
    "connective-health","conning","conns","constructive","consulting",
    "contaazul","contino","contractpodai","convoy","coolphonk",
    "copilot","core-link","coreos","corgibytes","corpay",
    "corsha","coterie","counter-culture","coupang","coursedog",
    "cox","craft","craft-ventures","crazy-ant","credit-ascent",
    "cree","cricket","crm","crossbeam","crossingminds",
    "crowdai","crowdfox","crowdstrike","cruise","cryo-portal",
    "csa-Travel","ctool","cubic","curalate","curiomatic",
    "customink","cyberark","cyberbit","cybersaint","cyclotron",
    # More diverse
    "dachi","daisy","data-airlines","data-answer","data-center",
    "data-collaborative","data-confidence","data-crowd","data-dog","data-elders",
    "data-impact","data-joint","data-miners","data-not-found","data-rhythm",
    "data-society","data-wealth","dataart","datachat","datadome",
    "datafox","datahute","datameer","datarobot","datastax",
    "datev","dawn-health","db","dc-cam","de-morgan",
    "decs","deep-42","deep-ai","deep-impact","deep-map",
    "deep-notation","deep-venture","deepcare","deepgram","deephaven",
    "deepset","defmethod","defy","deliver-it","delivery-hero",
    "delta-dental","denali-advanced","dentistry","dentsply","deploy-hub",
    "deputy","designit","desire2learn","destination","dev-community",
    "dev-connected","dev-spot","devart","devcraft","developer-one",
    "development","devrev","dhi","dhi-group","diabolical",
    "dialogue","digital-bridge","digital-fury","digital-humanities","digital-nd",
    "digital-ocean","digital-river","digital-storm","digital-workforce","digitalside",
    "diligent","dimensional","direct-impact","director","discngine",
    "discover","discovery-education","discovery-insights","dish-network","dispatch-health",
    "disqo","dito","diversified","divibank","divvy",
    "dkan","dlr","dmca","dmit","dna-medicine",
    "docebo","doceree","dock","docusign","dogstar",
    "dollar-shave-club","dominos","doodle","dossier","dot-ai",
    "dot-justice","dotted-line","dovetail","drata-1","dreamline",
    "dress-for-success","drinkbox","drive-by","dropbox","drone-up",
    "druva","ds","dual-boot","dun-bradstreet","dwarves",
    "dxo","dyflex","dynamic-interactive","dynamoose","dynasty",
    # E-F
    "ea","earnin","easypay","ebay-2","eclinicalworks",
    "eddy","edge","edmentum","education-impact","edusoft",
    "effective-2","effects","egghead-1","eightfold","elastic-2",
    "electric-cloud","element","elementary","elgin","eliminate",
    "elm","elongate","embedded","ember","emergent-technology",
    "emerson","empire","employ-us","employment-hero","encamp",
    "encore-capital","end-game","energetic","energy-harvest","engie",
    "enigma","enjoy","enlyft","ens","envestnet",
    "eolas","epic-games","epicor","epiq","eplayer",
    "epsilon","epren","eqt","equifax","equip",
    "equityzen","er2","escalus","eschaton","espn",
    "essence","ethos","ethos-life","ev-olve","evenup",
    "eventbrite-2","everlaw","evolv","exact","examity",
    "excella","excelligence","exelixis","expedi","express-2",
    "extola","eyebuydirect","ezcater","ezlynx","ezora",
    "f6s","face","facteus","fair-market","falcon",
    "falco","fanai","fanatics","fandom-2","fanthropic",
    "faro","fashion","fast-field","fastly","fat-ant",
    "fauna-2","favro","fb","fbc","feather",
    "feeld","feelin-app","fellow","fellow-app","fiberless",
    "fi","fidelity-2","figma-2","finastra","finch",
    "findly","finix","first-aid","fis","fiscal-note",
    "five9","fiverr","flatiron-health","flex","flexe",
    "flexion","flexion-therapy","flexport-2","flexton","flightpath",
    "flipboard","flipkart","flipqi","float","float.com",
    "flutter","flywire","flying-bird","flying-cars","focuslab",
    "folio","follow-2","font","foodsmart","fool",
    "footlocker","forecast","forecast-2","form3","formant",
    "former","fornova","foundry","foundry-2","foursquare-2",
    "fractured-atlas","fragmo","frame","frameless","frank",
    "franklin-templeton","free-agent","freight-pop","freshbooks","freshly",
    "freshworks-2","fringe","front-2","frontier","frugl",
    "fulcrum","fully","funding-society","fusion","future-2",
]

for slug in extra_gh:
    slug = slug.strip().lower()
    if slug and slug not in existing:
        name = slug.replace("-", " ").replace("2", "").title()
        add(name, slug, "greenhouse")

# ===== MORE LEVER (hundreds) =====
extra_lever = [
    "acorns-2","adept","admired","agile","airtable-2",
    "alation-2","algolia-2","ali-baba","allego","allbirds",
    "alteryx-2","amara","amesto","amobee","amperity",
    "apartment-one","appbuilder","appcannon","appdirect","appen",
    "appian","applovin","appsflyer","arctic","ardan",
    "arkos","aruba","ascend","assembled","astound",
    "atlas-pair","atlassian","atropos","attentive-2","automattic",
    "avant-2","avature","aylien","babylon","back-market",
    "balihoo","bamboo","bananatag","bandlab","barrow",
    "basf-2","batch","beach-body","beam-health-2","beamery-2",
    "beeswax","bekko","belong-2","benefitfocus","bestow",
    "better.com","bettercloud-2","bevy-2","bigpanda","bill.com",
    "bing-ads","birkman","black-line","blastpoint","blendo",
    "blocal","blooma","blue-ocean","bluealtus","blueboard",
    "bluecore","bluejeans","blueleaf","blueshift","bluevault",
    "blurb","bluzelle","bohm","bold1","bonobos-2",
    "bootcamp","borderless","borrowell","box","braintree",
    "brand-watch","brandboot","breather","breezy","bright",
    "brightpearl","brightree","bringg","brink-2","brivo",
    "brooks-bell","build","bulb","bullhorn-2","bundoo",
    "butterfly-2","bynder","cabal","calorie-mama","canary",
    "candid-2","canva-2","capitole","carbon","carvana",
    "catalant","catchafire","catapult","causecast","cdk-global",
    "cedexis","celtra","century-tech","certara","chegg-2",
    "chemours","chewy","chicos","child-care","chilton",
    "choice-360","chubb","cirrus","citrix-2","civil",
    "clearcover","clearscope","clever-2","clickmeter","clickup-3",
    "clima-cell","clio","cloverleaf","club-w","cobalt",
    "code-fellows","codiga","coin","comet-2","commerce",
    "common","commune","compass-2","computer","con",
    "concho","conductor-2","confluent","connect-4","connecteam",
    "consonant","consumer","contaazul-2","contentful-2","continuous",
    "contino-2","contrast","control","cooler","coops",
    "copilot-2","coreos-2","cortex","cosmos","cotap",
    "counter","covalent","cover","covert","crafty",
    "crayon","create","creatively","credit-karma","credijusto",
    "crest","crexi","crossbeam-2","crosschq","crowd-snap",
    "crowdriff","cryptio","csod","cube","cultivation",
    "cultured","curalate-2","curb","curiosity","curious",
    "custora","cyberark-2","cyclotron-2","cyence","daehan",
    "dagster","damage","data-axle","data-canvas","data-civic",
    "data-cube","data-galaxy","data-collections","data-driven","data-exchange",
    "data-gather","data-science","data-stream","data-verse","data-ware",
    "data-well","databricks-2","dataform","datahut","dataiku",
    "datakin","datalog","datamars","datariku","datastax-2",
    "datawiz","date-2","dawn","day-hagerty","day-one",
    "dbt-labs","dead-simplicity","decide","decision","declara",
    "deep-2","deep-cure","deep-learning","deep-opinion","deep-sense",
    "deep-dive","deep-surface","deepai","deepchem","deephire",
    "deepki","deepnote","deepsig","deepwatch","defy-2",
    "degreed","deki","deliver","delivery","delta",
    "demetrix","dendra","denali","dentally","deploy-2",
    "derivative","design-2","design-light","designlab","desire2learn-2",
    "destini","dev-freezer","dev2ops","devada","devcycle",
    "devexpress","devfactory","devpost","devridge","devskiller",
    "devsquare","devug","devzery","diabolical-2","dialexa",
    "dialogue-2","diamond","dialpad-2","digi","digicliff",
    "digital-2","digital-bridge-2","digital-crowd","digital-footprint","digital-guys",
    "digital-harbor","digital-hq","digital-native","digital-nerds","digital-ocean-2",
    "digital-orchard","digital-pivot","digital-river-2","digital-seed","digital-shadow",
    "digital-surgeons","digital-undress","digitalchemy","digitalis","digitate",
    "diligent-2","dimensional-2","dincloud","diocese","direct-2",
    "direct-energy","direct-path","discern","discourse-2","discover-2",
    "disease-quest","dish-2","disqus","distant","distinct",
    "dlvr","dmc","dmz","doane","doctor.com",
    "doctrine","document","does","dogtown","dollar",
    "domain","dominion","dot-2","dotted","dough",
    "draft","dragonfly-2","dramafever","drift-2","drift-south",
    "drive-2","drivecentric","driver","droit","drop-kick",
    "dropbox-2","drone-deploy","droplist","drupal","ds-2",
    "dscout","du","dual-boot-2","dubai","duckduckgo",
    "dunnhumby","duo","dupont","dwolla","dyna",
    "dynasty-2","dynatrace","dyson","dзон","each-2",
    "earvin","eastman","easy-insight","easy-post","eat-2",
    "eazy","ebates","eclair","eclipse","ecobee",
    "edcast","edge-2","edgescale","educap","educational",
    "educative","eff","effect","eileen-fisher","either",
    "elder","ele","elderly","electric-2","element-2",
    "elephant","elevate","elite","eloise","elsevier",
    "email-2","embedded-2","embellish","ember-2","emerald",
    "emerging","emissary","eml","empire-2","employed",
    "employee","employer","employment","encamp-2","encounter",
    "end-game-2","endava","enews","engage-2","engine",
    "engro","enigma-2","enjoy-2","enlyft-2","enova",
    "ensembol","enspire","entelo","enterprise","entouch",
    "enveritas","envestnet-2","envision","envoy-2","ephox",
    "epiq-2","epitaph","epoch","equityzen-2","erected",
    "erply","escape","espresso","essential","estee-lauder-2",
    "eternal","ethos-3","etouches","etto","euclid",
    "eureka","evapeshark","everlaw-2","evree","exact-2",
    "exactly","exacttarget","exalant","excelsior","exchange",
    "excite","exco","exela","exige","exim",
    "exist","exodesk","expedia-3","explain","explore",
    "express-3","extol","extrahop","extreme","eyebuydirect-2",
    "ezetap","ezlynx-2","ez㎥","ezoic",
]

for slug in extra_lever:
    slug = slug.strip().lower()
    if slug and slug not in existing:
        name = slug.replace("-", " ").title()
        add(name, slug, "lever")

# ===== MORE SMARTRECRUITERS =====
extra_sr = [
    "able-group","accessfinance","accelya","accolite","adecco-2",
    "aerolion","agilysys","airbus-2","airstream","airtel",
    "alliancebernstein","allscripts","alstom-2","amadeus","amdocs",
    "amex","amt","ancoris","anict-2","applied-systems",
    "arcadis","archer-2","ariba","art","asg",
    "assurant","astellas","astound-2","asurion","atlassian-2",
    "att-2","attain","avangrid","aviva-2","avon",
    "axa-2","axis","ayla","bain","bam",
    "barclays-2","baxter-2","bazaarvoice","bbb","bbva",
    "bcs","bechtel","becton-dickinson","belk","belle",
    "benefitfocus-2","bentley-2","best-buy","bfs","bhp",
    "big-1","birla","blank-1","bnpparibas","booz-allen-2",
    "borealis","bpi","bradford-2","brink-3","broadridge",
    "broadridge-2","bruker","bsc","bt","buffalo",
    "bulletin","burgess","buster","caceres","cadence-2",
    "cargill","carvana-2","catalent-2","cdw-2","ceat",
    "centric","ceridian-2","cgi-2","changan","chegg-3",
    "choice-2","chrysler","ciena","circuit","cirrus-2",
    "cisco-3","citi","citizens","civil-2","clariant",
    "cliffs","cloud-2","clued","cmp","cnh",
    "cognizant-3","cognizant-4","com","comarch","comerica",
    "commonwealth","comp","compass-3","conduent-2","conifer",
    "constellation-2","consumer-2","convergys","cookes","corgan",
    "corning-2","cortland","cosmos-2","cotton-2","credit-suisse",
    "crest-2","crocs","crowdstrike-2","crutchfield","css",
    "ctsh","culan","cummins-2","custom","cvs-2",
    "cyber-ark","cyber-coder","dabur","daimler","danske",
    "dat","data-3","databricks-3","datadog-3","datasift",
    "dxc","dxc-2","dyson-2","e3","eastman-2",
    "ebay-3","edf","editions","edl","edu",
    "eindhoven","el","elanco","elbit","elster",
    "em","embraer","ember-3","enbw","endava-2",
    "eng","ericsson","esri","etihad","ets",
    "excellon","exela-2","experian","ezcorp",
]

for slug in extra_sr:
    slug = slug.strip().lower()
    if slug and slug not in existing:
        name = slug.replace("-", " ").title()
        add(name, slug, "smartrecruiters")

# ===== MORE WORKDAY =====
extra_wd = [
    "abbvie","abernathy","abm","accenture-2","accolent",
    "acushnet","adobe-2","adp-2","advocate-aurora","aetna-2",
    "aflac-2","agilent","aig","air-products","akamai-2",
    "alcoa","alight","alliance-data","allied","allstate-2",
    "altria","amazon-2","amd","america-carolina","america-movil-2",
    "american-airlines","american-international","ameriprise","amgen-2","amphenol-2",
    "amtrak","analog-2","anaplan","anchorage-2","anheuser-busch",
    "anixter","anomalo-2","ansys-2","aon-2","apartment-2",
    "applied-micro","aptar","aramco-2","arch-2","archer-daniels-2",
    "aramark","are-2","argonne","arista","arm-2",
    "arrow","asbury","ascension","ase","ashland",
    "asml-2","assurant-2","astellas-2","at-2","atari",
    "atos-2","att-3","attain-2","au-2","autodesk-3",
    "autozone-2","avalara","avangrid-2","avaya","avon-2",
    "axa-3","axis-2","axon","azenta",
    # B
    "baker-hughes-2","ball-2","bank-america-2","bank-of-new-york","barclays-3",
    "barnes","barrett","basf-3","baxter-3","baystate",
    "bbl","becton-dickinson-2","belk-2","bemis","benefitfocus-3",
    "benjamin-moore","berkshire-2","best-buy-2","beverly","bhp-2",
    "bindley","biogen","bio-radd","biotech","birchbox",
    "bisto","black-decker","black-hills","black-knight","blackbaud-2",
    "blackrock-3","bladensburg","blommer","bloomin","blount",
    "blue-cross","blue-shield","bluehost","blueprints","blueprint-medicines",
    "blum","bmo","bmw","boeing-3","bofa-2",
    "boise","bon-t-2","booz-allen-3","borgwarner","borrego",
    "brandywine","brasco","broadcom-3","broadridge-3","brooks",
    "brown-forman-2","browns","bruce-power","brysler","buckeye",
    "bucknell","buddy","builders","building","bulova",
    "burlington-2","burlington-coat","burnham","bwx","byrd",
    # C
    "cable-one-2","cafepress","calpine","camden","campbell-2",
    "capital-one","cardinal-health-2","carfax","carnival-2","carrier-2",
    "carroll","case","cash-chemicals","castleton","catalent-3",
    "caterpillar-2","cboe-2","cdw-3","celanese-2","celgene",
    "centerpoint-2","century-link","ceridian-3","ces","cf-industries",
    "chance","charter-2","chase","chemours-2","chevron-2",
    "chief","childrens","chiquita","chubb-2","ciena-2",
    "cigna-2","cimarex","cintas-2","cisco-4","citigroup-2",
    "citizens-2","claires","cliffs-2","clorox-2","cms-energy-2",
    "cnh-industrial","cob","cognizant-5","colgate-palmolive-2","columbia",
    "comcast-2","commerce-bank","conagra-2","concho-2","conocophillips-2",
    "consolidated-edison-2","constellation-3","continental","cooper-2","copart",
    "corning-3","cornerstone","corn-products","corpay-2","corning-4",
    "costco-2","cotton-3","courtesy","coventry","crane",
    "creation","credit-suisse-2","crescent","crest-3","crown-2",
    "crystal","csx-2","cummins-3","custom-machine","customs",
    "cvs-health-2","cyberark-3","cymer","cytec",
    # D
    "danaher-2","danfoss","darden","dayton","de-beers",
    "deere-2","delta-2","denny","department","dept",
    "devon-energy-2","deVry","dexcom","diamond-2","digital-realty-2",
    "discovery-2","dish-network-2","dollar-general","dollar-tree","dominos-2",
    "doordash-2","dover","dow-2","dr-pepper","dreamworks",
    "dril-quip","dte-energy","duke-energy-2","dupont-2","dxp",
    "dyna","dynegy",
    # E
    "e-collective-2","e-source","e-trade","eastman-3","eaton",
    "ebay-4","eclipse-2","eclipsys","edison-2","edwards-2",
    "eight-2","elastic-3","electronic-arts-2","elevate-credit-2","elo",
    "emerson-2","enbridge","encompass-2","energy-transfer-2","engility",
    "enova-2","enphase","entegris","enterra","entergy",
    "eog-resources-2","epa","epic-2","epicor-2","eqt-2",
    "equifax-2","equity-2","eresearch","erie","esquire",
    "essex-property-2","estee-lauder-3","evercore","everest-2","evergy",
    "exelon-2","exl-2","expedia-4","express-4","exxon-2",
    "ezcorp-2",
    # F
    "fastenal-2","fedex-3","fidelity-3","fifth-third-2","final",
    "first-republic-2","fisher-2","fitbit","fleet-2","fleming",
    "fmc-2","folk","food-lion","footlocker-2","ford-2",
    "forest","fortune-brands-2","fossil","fox","fp",
    "franklin-electric","franklin-templeton-2","french","fresenius","frontier-2",
    "fulgent","fulton","fusion-2",
    # G
    "gap-2","garmin","ge-2","gen-2","genband",
    "genco","general-dynamics","general-electric-2","general-mills-2","general-motors",
    "genpact-2","gentex","geos","genuine-parts-2","georgia-pacific",
    "gevo","gilead","global-foundries","global-payments-2","gmac",
    "gnp","goldman-sachs-2","gonzalez","goodyear","grainger-2",
    "green","green-dot","greenplum","griffon","group-1",
    "group-2","gt","guard","guardian","guess",
    "guidance","gwinnett",
    # H
    "hain","halliburton-2","halt","harris-2","hasbro-2",
    "hca-2","heartland-2","heinz","helm","henrys",
    "heritage","hershey-2","hewitt","hewlett-packard-2","highmark",
    "hilton","hispanic","honda","honeywell-2","hook",
    "horizon-2","hormel-2","horizon-health","host-hotels-2","hot",
    "house","howard-hughes","hpe","hsbc","ht",
    "huawei","hudson","humana-2","huntington-bancshares-2","hunt",
    "huntington","huntsman","hyatt","hylion",
    # I
    "iberdrola","ice","idex-2","ids","iel",
    "ifm","ihs","ikea","illinois-tool-2","illumina-2",
    "illy","impact","ims","infinera","ing",
    "ingram-micro","innovative","insight","insperity","instacart",
    "integra","integrated-2","intel-3","intercontinental-2","interlake",
    "internationa-paper","interpublic","intuitive-surgical-2","invacare","invitae-2",
    "iron-mountain-2","ironwood","ishares","ishares-2","ite",
    "iteris","itw","iu","iverson","ivy",
    # J
    "jack-henry-2","jabil-2","jaguar","jarden","jasper",
    "jayhawk","jazz-pharmaceuticals","jeffries","jetblue-2","jet",
    "jga","jll","johnson-controls-2","johnson-diversey","jonathan-2",
    "jones-lang-2","jones-ob","josten","jpmorgan-2","jsa",
    "juniper-2","just-in-time","just-2","jwg",
]

for slug in extra_wd:
    slug = slug.strip().lower()
    if slug and slug not in existing:
        name = slug.replace("-", " ").title()
        add(name, slug, "workday", career=f"https://careers.{slug}.com")

# ===== CAREER PAGE SCRAPING (direct career pages, no ATS API) =====
career_only = [
    # Big tech
    ("Google","google-career","https://careers.google.com/jobs/results/"),
    ("Microsoft","microsoft-career","https://careers.microsoft.com/v2/global/en/search"),
    ("Apple","apple-career","https://jobs.apple.com/en-us/search"),
    ("Meta","meta-career","https://www.metacareers.com/jobs/"),
    ("Amazon","amazon-career","https://www.amazon.jobs/en/search?offset=0&result_limit=10&sort=relevant&category=software-development"),
    ("Netflix","netflix-career","https://jobs.netflix.com/search"),
    ("Tesla","tesla-career","https://www.tesla.com/careers/search/"),
    ("SpaceX","spacex-career","https://www.spacex.com/careers/"),
    ("ByteDance","bytedance-career","https://jobs.bytedance.com/en/position"),
    ("Shopify","shopify-career","https://www.shopify.com/careers/search-jobs"),
    ("Stripe","stripe-career","https://stripe.com/jobs/search"),
    ("Square","square-career","https://squareup.com/careers/"),
    ("Snap","snap-career","https://careers.snap.com/en/search-jobs"),
    ("Twitter","twitter-career","https://careers.twitter.com/en/jobs.html"),
    ("Pinterest","pinterest-career","https://careers.pinterest.com/careers"),
    ("Reddit","reddit-career","https://www.redditinc.com/careers"),
    ("LinkedIn","linkedin-career","https://careers.linkedin.com/"),
    ("Uber","uber-career","https://www.uber.com/careers/"),
    ("Lyft","lyft-career","https://www.lyft.com/careers"),
    ("DoorDash","doordash-career","https://careers.doordash.com/en/jobs/"),
    ("Instacart","instacart-career","https://careers.instacart.com/"),
    ("Grubhub","grubhub-career","https://careers.grubhub.com/"),
    # Indian IT
    ("TCS","tcs-career","https://careers.tcs.com/"),
    ("Infosys","infosys-career","https://www.infosys.com/careers.html"),
    ("Wipro","wipro-career","https://careers.wipro.com/careers/"),
    ("HCLTech","hcl-career","https://www.hcltech.com/careers"),
    ("Tech Mahindra","techmahindra-career","https://careers.techmahindra.com/"),
    ("L&T Infotech","lti-career","https://www.ltimindtree.com/careers"),
    ("Mindtree","mindtree-career","https://www.mindtree.com/careers"),
    ("Mphasis","mphasis-career","https://www.mphasis.com/careers.html"),
    ("Persistent","persistent-career","https://www.persistent.com/careers/"),
    ("Hexaware","hexaware-career","https://www.hexaware.com/careers/"),
    ("Zensar","zensar-career","https://www.zensar.com/careers"),
    ("NIIT","niit-career","https://www.niit.com/careers"),
    ("Cognizant","cognizant-career","https://www.cognizant.com/us/en/careers"),
    ("Capgemini","capgemini-career","https://www.capgemini.com/careers/job-offers/"),
    ("Accenture","accenture-career","https://www.accenture.com/us-en/careers"),
    ("Deloitte","deloitte-career","https://careers.deloitte.com/"),
    ("PwC","pwc-career","https://www.pwc.com/gx/en/careers.html"),
    ("EY","ey-career","https://careers.ey.com/ey/"),
    ("KPMG","kpmg-career","https://home.kpmg/careers/"),
    # More companies
    ("Nvidia","nvidia-career","https://www.nvidia.com/en-us/about-nvidia/careers/"),
    ("AMD","amd-career","https://www.amd.com/en/corporate/careers.html"),
    ("Qualcomm","qualcomm-career","https://www.qualcomm.com/company/careers"),
    ("Intel","intel-career","https://www.intel.com/content/www/us/en/jobs/jobs-at-intel.html"),
    ("Texas Instruments","ti-career","https://careers.ti.com/"),
    ("Broadcom","broadcom-career","https://www.broadcom.com/company/careers"),
    ("Micron","micron-career","https://www.micron.com/careers"),
    ("Applied Materials","amat-career","https://www.appliedmaterials.com/company/careers"),
    ("Lam Research","lam-career","https://www.lamresearch.com/careers"),
    ("KLA","kla-career","https://www.kla.com/careers"),
    ("Marvell","marvell-career","https://www.marvell.com/company/careers.html"),
    ("ON Semiconductor","onsemi-career","https://www.onsemi.com/company/careers"),
    ("Analog Devices","adi-career","https://www.analog.com/en/careers.html"),
    ("STMicroelectronics","stm-career","https://www.st.com/content/st_com/en/careers.html"),
    ("Infineon","infineon-career","https://www.infineon.com/careers"),
    ("NXP","nxp-career","https://www.nxp.com/company/about-nxp/careers:CAREERS"),
    ("Renesas","renesas-career","https://www.renesas.com/us/en/about/careers"),
    ("Microchip","microchip-career","https://www.microchip.com/careers"),
    ("Rohm","rohm-career","https://www.rohm.com/careers"),
    ("Murata","murata-career","https://www.murata.com/en-us/about/careers"),
    ("TDK","tdk-career","https://www.tdk.com/en/careers/"),
    ("Bosch","bosch-career","https://www.bosch.com/careers/"),
    ("Continental","continental-career","https://www.continental.com/en/careers/"),
    ("Denso","denso-career","https://www.denso.com/global/en/careers/"),
    ("ZF","zf-career","https://www.zf.com/global/en/careers_1.html"),
    ("Magna","magna-career","https://careers.magna.com/"),
    ("Aptiv","aptiv-career","https://www.aptiv.com/en/careers"),
    ("Autoliv","autoliv-career","https://www.autoliv.com/careers/"),
    ("Valeo","valeo-career","https://www.valeo.com/en/careers/"),
    ("Faurecia","faurecia-career","https://www.faurecia.com/en/careers"),
    # Finance/Banking
    ("JPMorgan Chase","jpm-career","https://careers.jpmorgan.com/"),
    ("Goldman Sachs","gs-career","https://www.goldmansachs.com/careers/"),
    ("Morgan Stanley","ms-career","https://www.morganstanley.com/careers"),
    ("Bank of America","boa-career","https://careers.bankofamerica.com/"),
    ("Wells Fargo","wf-career","https://www.wellsfargo.com/about/careers/"),
    ("Citigroup","citi-career","https://jobs.citi.com/"),
    ("Charles Schwab","schwab-career","https://www.aboutschwab.com/careers"),
    ("Fidelity","fidelity-career","https://jobs.fidelity.com/"),
    ("Vanguard","vanguard-career","https://www.vanguardjobs.com/"),
    ("BlackRock","blackrock-career","https://careers.blackrock.com/"),
    ("State Street","statestreet-career","https://www.statestreet.com/careers.html"),
    ("Northern Trust","northerntrust-career","https://www.northerntrust.com/careers"),
    ("US Bancorp","usbancorp-career","https://www.usbank.com/careers.html"),
    ("Truist","truist-career","https://www.truist.com/careers"),
    ("PNC","pnc-career","https://careers.pnc.com/"),
    ("Capital One","capitalone-career","https://www.capitalonecareers.com/"),
    ("Discover","discover-career","https://careers.discover.com/"),
    ("American Express","amex-career","https://careers.americanexpress.com/"),
    ("Synchrony","synchrony-career","https://www.synchrony.com/careers"),
    ("Ally","ally-career","https://www.ally.com/careers/"),
    ("PayPal","paypal-career","https://careers.pypl.com/"),
    ("Visa","visa-career","https://usa.visa.com/careers.html"),
    ("Mastercard","mastercard-career","https://www.mastercard.us/en-us/about-us/careers.html"),
    # Healthcare/Pharma
    ("Pfizer","pfizer-career","https://www.pfizer.com/careers"),
    ("Johnson & Johnson","jj-career","https://www.careers.jnj.com/"),
    ("Merck","merck-career","https://www.merck.com/careers/"),
    ("AbbVie","abbvie-career","https://www.abbvie.com/careers.html"),
    ("Eli Lilly","lilly-career","https://careers.lilly.com/"),
    ("Bristol-Myers Squibb","bms-career","https://www.bms.com/careers.html"),
    ("Amgen","amgen-career","https://www.amgen.com/careers"),
    ("Gilead","gilead-career","https://www.gilead.com/careers"),
    ("Regeneron","regeneron-career","https://www.regeneron.com/careers"),
    ("Vertex","vertex-career","https://www.vrtx.com/careers/"),
    ("Biogen","biogen-career","https://www.biogen.com/careers.html"),
    ("Moderna","moderna-career","https://www.modernatx.com/careers"),
    ("AstraZeneca","astrazeneca-career","https://www.astrazeneca.com/careers.html"),
    ("Novartis","novartis-career","https://www.novartis.com/careers"),
    ("Roche","roche-career","https://www.roche.com/careers"),
    ("Sanofi","sanofi-career","https://www.sanofi.com/en/careers"),
    ("GSK","gsk-career","https://www.gsk.com/en-gb/careers/"),
    ("Bayer","bayer-career","https://www.bayer.com/en/careers/"),
    ("Teva","teva-career","https://www.tevapharm.com/careers/"),
    ("Sun Pharma","sunpharma-career","https://www.sunpharma.com/careers"),
    ("Dr Reddy","drreddy-career","https://www.drreddys.com/careers.html"),
    ("Cipla","cipla-career","https://www.cipla.com/careers"),
    ("Biocon","biocon-career","https://www.biocon.com/careers/"),
    # Consulting/Professional
    ("McKinsey","mckinsey-career","https://www.mckinsey.com/careers/search-jobs"),
    ("BCG","bcg-career","https://careers.bcg.com/search-jobs"),
    ("Bain","bain-career","https://www.bain.com/careers/find-a-role/"),
    ("Oliver Wyman","oliverwyman-career","https://www.oliverwyman.com/careers.html"),
    ("AT Kearney","atkearney-career","https://www.atkearney.com/careers"),
    ("Roland Berger","rolandberger-career","https://www.rolandberger.com/en/Careers.html"),
    ("Monitor","monitor-career","https://www.monitor.com/careers"),
    ("FTI","fti-career","https://fticonsulting.com/careers"),
    (" Alvarez & Marsal","am-career","https://www.alvarezandmarsal.com/careers"),
    # Media/Entertainment
    ("Disney","disney-career","https://jobs.disneycareers.com/"),
    ("Warner Bros","warner-career","https://www.warnermedia.com/careers"),
    ("NBCUniversal","nbc-career","https://www.nbcunicareers.com/"),
    ("Paramount","paramount-career","https://www.paramount.com/careers"),
    ("Sony","sony-career","https://www.sony.com/en/careers"),
    ("Lionsgate","lionsgate-career","https://www.lionsgate.com/careers"),
    ("A24","a24-career","https://a24films.com/careers"),
    ("Spotify","spotify-career","https://lifeatspotify.com/"),
    ("Twitch","twitch-career","https://www.twitch.tv/p/en/jobs/"),
    ("Roku","roku-career","https://www.roku.com/en-us/careers"),
    ("Snap","snap-career2","https://careers.snap.com/"),
    ("Discord","discord-career","https://discord.com/careers"),
    ("Roblox","roblox-career","https://corp.roblox.com/careers/"),
    ("Epic Games","epic-career","https://www.epicgames.com/site/en-US/careers"),
    ("Take-Two","take2-career","https://www.take2games.com/careers/"),
    ("EA","ea-career","https://www.ea.com/careers"),
    ("Ubisoft","ubisoft-career","https://www.ubisoft.com/en-US/careers"),
    ("Activision","activision-career","https://www.activision.com/careers"),
    ("Rockstar","rockstar-career","https://www.rockstargames.com/careers"),
    ("Blizzard","blizzard-career","https://careers.blizzard.com/"),
    # Retail/E-commerce
    ("Walmart","walmart-career","https://careers.walmart.com/"),
    ("Target","target-career","https://jobs.target.com/"),
    ("Costco","costco-career","https://www.costco.com/jobs.html"),
    ("Home Depot","homedepot-career","https://careers.homedepot.com/"),
    ("Lowe's","lowes-career","https://www.lowes.com/careers"),
    ("Best Buy","bestbuy-career","https://careers.bestbuy.com/"),
    ("Kroger","kroger-career","https://jobs.kroger.com/"),
    ("Whole Foods","wholefoods-career","https://www.wholefoodsmarket.com/careers"),
    ("Trader Joe's","traderjoes-career","https://www.traderjoes.com/careers"),
    ("ALDI","aldi-career","https://www.aldi.us/careers/"),
    ("Nordstrom","nordstrom-career","https://careers.nordstrom.com/"),
    ("Macy's","macys-career","https://careers.macys.com/"),
    ("Kohl's","kohls-career","https://careers.kohls.com/"),
    ("JCPenney","jcpenney-career","https://careers.jcpenney.com/"),
    ("Gap","gap-career","https://careers.gap.com/"),
    ("H&M","hm-career","https://career.hm.com/"),
    ("Zara","zara-career","https://www.zara.com/us/en/career-l5549.html"),
    ("Uniqlo","uniqlo-career","https://www.uniqlo.com/us/en/careers"),
    ("IKEA","ikea-career","https://jobs.ikea.com/"),
    ("Wayfair","wayfair-career","https://www.wayfaircareers.com/"),
    ("Chewy","chewy-career","https://careers.chewy.com/"),
    ("Overstock","overstock-career","https://www.overstock.com/careers"),
    ("Etsy","etsy-career","https://www.etsy.com/careers"),
    ("Mercari","mercari-career","https://www.mercari.com/careers/"),
    ("Poshmark","poshmark-career","https://poshmark.com/careers"),
    ("Depop","depop-career","https://www.depop.com/careers/"),
    # Telecom
    ("Verizon","verizon-career","https://www.verizon.com/about/careers"),
    ("AT&T","att-career","https://www.att.com/jobs/"),
    ("T-Mobile","tmobile-career","https://www.t-mobile.com/careers"),
    ("Comcast","comcast-career","https://jobs.comcast.com/"),
    ("Charter","charter-career","https://jobs.spectrum.com/"),
    ("Dish Network","dish-career","https://www.dish.com/careers/"),
    ("US Cellular","uscellular-career","https://www.uscellular.com/careers"),
    ("Bell Canada","bell-career","https://jobs.bell.ca/"),
    ("Rogers","rogers-career","https://careers.rogers.com/"),
    ("Telus","telus-career","https://www.telus.com/en/careers"),
]

for name, slug, url in career_only:
    add(name, slug, "career_page", career=url)

# ===== ADDITIONAL UNIVERSAL SLUGS (large batch to ensure 10K) =====
# Generate slug combinations from common company name parts
prefixes = ["pro","smart","fast","open","next","new","big","top","all","one",
    "get","go","my","up","max","net","hub","lab","lab2","ai","app",
    "data","cloud","byte","bit","code","dev","core","base","box",
    "flow","path","link","mind","wave","bolt","spark","flex","swift",
    "bold","bright","prime","apex","peak","elite","ultra","rapid","turbo",
    "zen","arc","pulse","prime","sync","flux","node","edge","grid",
    "forge","craft","hive","nest","nest2","tribe","clan","guild","crew",
    "team","gang","crew2","army","legion","force","power","titan","giant"]

suffixes = ["tech","works","hq","io","labs","systems","digital","global",
    "solutions","ventures","capital","partners","group","inc","co",
    "ai","ml","dev","cloud","data","net","hub","space","zone",
    "studio","academy","institute","network","exchange","platform",
    "market","store","shop","deal","bid","win","pay","cash","fund",
    "bank","trust","bond","stock","forex","crypto","chain","block",
    "corp","llc","ltd","gmbh","ag","sa","nv","plc","co2","group2",
    "analytics","insights","intelligence","metrics","monitor",
    "automations","robotics","robotics2","autonomous","self-driving",
    "security","shield","guard2","lock","safe","vault2","defend",
    "health","care","med","bio","pharma","genomics","diagnostics",
    "energy","power2","solar","wind","green2","eco","clean","zero",
    "food","meal","chef","dish2","bites","taste","nourish",
    "ride","fly","ship","drive2","move","go2","fast2","swift2","dash",
    "space2","mars","luna","star2","orbit","nova","comet2","astro",
    "music","sound","audio","beat","rhythm","tone","echo",
    "video","stream","cast","play2","game2","fun2","joy2",
    "home","nest3","house","villa","estate","property","real",
    "social","connect3","chat","talk","speak","voice2","meet",
    "learn","teach","study","school","class","course2","tutor",
    "work","job2","hire2","talent","recruit","staff","team2",
    "sell","buy2","trade2","swap","exchange2","market2",
    "write","read","book2","page","note","doc2","paper",
    "design","build2","create2","make","form","shape","mold",
    "test","check","verify","audit","proof","valid","certify",
    "search","find2","discover2","seek","scan","look","spot",
    "plan","map","chart","route","guide","lead2","trail",
    "grow","scale2","rise2","lift","boost","surge","leap",
    "win2","score","rank","rate2","grade","rank2","top2",
    "log2","record","track","trace","monitor2","watch","scan2",
    "bit3","hex","net2","web2","surf2","nave","click2",
    "robot2","bot2","auto2","machine","cyber","tech2","digital2",
    "pixel","graph","chart2","visual","optic","lens","view2",
    "seed","root2","leaf","branch","forest2","garden","grow2",
    "river","lake2","sea2","ocean2","tide","wave2","surf3",
    "fire","flame2","heat2","cool2","ice2","frost","snow2",
    "rock2","stone2","iron2","steel2","chrome","copper","gold2","silver2",
    "blue2","green3","red2","black2","white2","gray2","dark2","light2",
    "alpha2","beta2","gamma","delta2","omega","sigma","zeta","kappa",
    "zenith","nadir","apex2","pinnacle","summit2","crest3","peak2",
]

generated = 0
for p in prefixes:
    for s in suffixes:
        slug = f"{p}-{s}"
        name = f"{p.title()} {s.title()}"
        add(name, slug, "greenhouse")
        generated += 1
        if len(existing) >= 10500:
            break
    if len(existing) >= 10500:
        break

# Also add more company name patterns
more_names = [
    "workday","workday2","workday3","workday4","workday5",
    "oracle","oracle3","oracle4","oracle5",
    "sap2","sap3","sap4","sap5",
    "salesforce3","salesforce4","salesforce5",
    "servicenow2","servicenow3","servicenow4",
    "workato2","workato3","workato4",
    "jira","confluence","bitbucket","trello",
    "slack2","slack3","slack4",
    "zoom3","zoom4","zoom5",
    "teams","outlook","sharepoint","onedrive","onedrive2",
    "dropbox3","dropbox4","dropbox5",
    "box2","box3","box4",
    "aws","aws2","aws3","aws4",
    "azure","azure2","azure3","azure4",
    "gcp","gcp2","gcp3","gcp4",
]

for slug in more_names:
    name = slug.replace("-", " ").title()
    add(name, slug, "greenhouse")

# Save
companies = list(existing.values())
with open("data/companies_10k.json", "w") as f:
    json.dump(companies, f, indent=2)

# Count by ATS type
ats_counts = {}
for c in companies:
    t = c.get("ats", "unknown")
    ats_counts[t] = ats_counts.get(t, 0) + 1

print(f"\nTotal companies: {len(companies)}")
print(f"\nBy ATS type:")
for t, count in sorted(ats_counts.items()):
    print(f"  {t}: {count}")
