"""ALL job keywords for scraping. 600+ keywords across every industry."""

TECH_KEYWORDS = [
    # Software Engineering
    "software engineer", "software developer", "senior software engineer",
    "staff engineer", "principal engineer", "lead engineer", "engineering manager",
    "python developer", "java developer", "javascript developer", "typescript developer",
    "C++ developer", "C# developer", "golang developer", "rust developer",
    "ruby developer", "php developer", "swift developer", "kotlin developer",
    "scala developer", "perl developer", "R developer", "matlab developer",
    # Web
    "full stack developer", "frontend developer", "backend developer",
    "web developer", "react developer", "angular developer", "vue developer",
    "node.js developer", "next.js developer", "laravel developer", "django developer",
    "flask developer", "rails developer", "wordpress developer", "shopify developer",
    "web designer", "web administrator",
    # Mobile
    "mobile developer", "iOS developer", "android developer",
    "react native developer", "flutter developer", "swift developer",
    "mobile app developer", "cross-platform developer",
    # Data
    "data scientist", "data analyst", "data engineer", "data architect",
    "data warehouse engineer", "ETL developer", "BI developer",
    "business intelligence analyst", "report developer", "tableau developer",
    "power BI developer", "SQL developer", "big data engineer",
    "Hadoop developer", "spark developer", "kafka developer",
    "data platform engineer", "analytics engineer",
    # AI / ML
    "machine learning engineer", "ML engineer", "AI engineer",
    "deep learning engineer", "NLP engineer", "computer vision engineer",
    "AI researcher", "prompt engineer", "LLM engineer",
    "MLOps engineer", "AI product manager", "data science manager",
    # DevOps / Cloud
    "devops engineer", "site reliability engineer", "SRE",
    "cloud architect", "cloud engineer", "AWS engineer", "Azure engineer",
    "GCP engineer", "platform engineer", "infrastructure engineer",
    "CI/CD engineer", "release engineer", "build engineer",
    "terraform engineer", "kubernetes engineer", "docker engineer",
    # Security
    "security engineer", "cybersecurity analyst", "information security analyst",
    "penetration tester", "ethical hacker", "security architect",
    "SOC analyst", "incident response analyst", "forensics analyst",
    "GRC analyst", "compliance analyst", "vulnerability analyst",
    # QA / Testing
    "QA engineer", "QA analyst", "test engineer", "automation engineer",
    "SDET", "performance engineer", "load testing engineer",
    "manual tester", "test analyst", "quality engineer",
    # Other Tech
    "UX designer", "UI designer", "UX researcher", "UX engineer",
    "product designer", "interaction designer", "visual designer",
    "graphic designer", "design engineer",
    "network engineer", "network administrator", "systems administrator",
    "system administrator", "Linux administrator", "Windows administrator",
    "database administrator", "DBA", "Oracle DBA", "SQL Server DBA",
    "IT support", "IT technician", "help desk", "desktop support",
    "IT manager", "IT director", "CTO", "VP of engineering",
    "technical lead", "scrum master", "product owner", "agile coach",
    "release manager", "configuration manager", "release train engineer",
    "blockchain developer", "solidity developer", "web3 developer",
    "game developer", "unity developer", "unreal engine developer",
    "AR developer", "VR developer", "XR developer",
    "embedded systems engineer", "firmware engineer", "IoT engineer",
    "robotics engineer", "automation engineer", "RPA developer",
    "technical writer", "API documentation writer", "developer advocate",
    "developer relations", "evangelist", "solutions architect",
    "presales engineer", "systems engineer", "sales engineer",
]

HEALTHCARE_KEYWORDS = [
    "registered nurse", "RN", "licensed practical nurse", "LPN",
    "nurse practitioner", "NP", "clinical nurse specialist",
    "certified nursing assistant", "CNA", "patient care technician",
    "medical assistant", "MA", "phlebotomist",
    "dental hygienist", "dental assistant", "dental office manager",
    "pharmacist", "pharmacy technician", "pharmacy manager",
    "physical therapist", "PT", "physical therapy assistant",
    "occupational therapist", "OT", "occupational therapy assistant",
    "respiratory therapist", "RT", "pulmonary function technologist",
    "radiology technician", "X-ray technician", "CT technologist",
    "MRI technologist", "ultrasound technician", "sonographer",
    "nuclear medicine technologist", "radiation therapist",
    "medical laboratory technician", "lab technician", "lab technologist",
    "medical coder", "medical biller", "medical billing specialist",
    "healthcare administrator", "hospital administrator",
    "clinical research coordinator", "clinical research associate",
    "clinical data manager", "regulatory affairs specialist",
    "medical records clerk", "health information technician",
    "patient care coordinator", "care coordinator", "case manager",
    "home health aide", "hospice aide", "medical transporter",
    "EMT", "paramedic", "EMT basic", "EMT advanced",
    "speech language pathologist", "speech therapist",
    "audiologist", "hearing instrument specialist",
    "optometrist", "optician", "ophthalmic assistant",
    "veterinary technician", "vet tech", "veterinarian",
    "veterinary assistant", "animal health technician",
    "surgical technician", "surgical technologist",
    "operating room nurse", "OR nurse", "circulating nurse",
    "anesthesia technician", "certified registered nurse anesthetist",
    "midwife", "certified nurse midwife", "lactation consultant",
    "medical director", "chief medical officer", "nurse manager",
    "unit manager", "charge nurse", "staff nurse",
    "clinical nurse manager", "nursing supervisor", "DON",
    "WIC coordinator", "community health worker",
    "social worker", "mental health counselor",
    "behavioral health technician", "substance abuse counselor",
    "rehabilitation counselor", "rehabilitation therapist",
    "chiropractor", "acupuncturist", "massage therapist",
    "dietitian", "registered dietitian", "nutritionist",
    "health educator", "wellness coach", "health coach",
    "clinical psychologist", "psychologist", "psychiatrist",
    "physician", "doctor", "surgeon", "internist",
    "family medicine doctor", "pediatrician", "OB/GYN",
    "cardiologist", "orthopedic surgeon", "dermatologist",
    "physician assistant", "PA", "PA-C",
    "medical office assistant", "front desk medical",
    "insurance verification specialist", "prior authorization specialist",
    "utilization review nurse", "quality assurance nurse",
    "infection preventionist", "epidemiologist",
]

BLUE_COLLAR_KEYWORDS = [
    "electrician", "journeyman electrician", "master electrician",
    "apprentice electrician", "industrial electrician", "maintenance electrician",
    "lineman", "power lineman", "electrician helper",
    "plumber", "licensed plumber", "journeyman plumber",
    "plumbing apprentice", "pipefitter", "steamfitter",
    "sprinkler fitter", "plumbing technician",
    "carpenter", "finish carpenter", "rough carpenter",
    "cabinet maker", "framing carpenter", "trim carpenter",
    "carpentry apprentice", "woodworker", "furniture maker",
    "welder", "MIG welder", "TIG welder", "stick welder",
    "welding apprentice", "fabricator", "metal fabricator",
    "welding inspector", "certified welder",
    "HVAC technician", "HVAC installer", "HVAC mechanic",
    "HVAC apprentice", "refrigeration technician", "HVAC service technician",
    "sheet metal worker", "duct installer",
    "mechanic", "auto mechanic", "automotive technician",
    "diesel mechanic", "diesel technician",
    "small engine mechanic", "motorcycle mechanic",
    "marine mechanic", "boat mechanic",
    "heavy equipment mechanic", "fleet mechanic",
    "transmission specialist", "brake technician",
    "tire technician", "alignment specialist",
    "automotive painter", "auto body repair",
    "collision repair technician", "auto glass installer",
    "detailer", "car detailer", "detail technician",
    "construction worker", "laborer", "general laborer",
    "construction laborer", "construction helper",
    "construction manager", "project manager construction",
    "general contractor", "site supervisor", "site foreman",
    "foreman", "crew leader", "construction foreman",
    "heavy equipment operator", "excavator operator",
    "bulldozer operator", "backhoe operator",
    "crane operator", "tower crane operator",
    "forklift operator", "reach truck operator",
    "loader operator", "grader operator",
    "compactor operator", "pile driver operator",
    "mason", "bricklayer", "stone mason",
    "concrete finisher", "concrete worker", "cement mason",
    "block layer", "pointer caulked",
    "painter", "house painter", "industrial painter",
    "commercial painter", "spray painter", "paint applicator",
    "drywall installer", "drywall finisher", "drywall hanger",
    "ceiling installer", "acoustical installer",
    "flooring installer", "tile installer", "carpet installer",
    "hardwood floor installer", "vinyl installer", "laminate installer",
    "roofer", "commercial roofer", "residential roofer",
    "roofing installer", "shingle installer", "flat roofer",
    "siding installer", "insulation installer", "blown-in insulation",
    "landscape", "landscaper", "landscape installer",
    "lawn care", "lawn maintenance", "mowing",
    "arborist", "tree trimmer", "tree removal",
    "irrigation technician", "landscape foreman",
    "pest control technician", "pest control operator",
    "fumigator", "termite technician",
    "appliance repair technician", "appliance installer",
    "elevator mechanic", "elevator installer",
    "fire alarm technician", "security system installer",
    "solar panel installer", "solar technician",
    "wind turbine technician", "wind energy technician",
    "well driller", "water well driller",
    "septic tank installer", "septic system technician",
    "asbestos removal", "hazmat technician", "abatement worker",
    "demolition worker", "demolition operator",
]

MANUFACTURING_KEYWORDS = [
    "manufacturing associate", "manufacturing operator",
    "assembly line worker", "production worker",
    "production operator", "machine operator",
    "packaging worker", "packaging operator", "packer",
    "shipping clerk", "shipping and receiving",
    "receiving clerk", "material handler",
    "quality control inspector", "quality inspector", "QC inspector",
    "quality assurance technician", "QA technician",
    "CNC machinist", "CNC operator", "CNC programmer",
    "manual machinist", "tool and die maker",
    "mill operator", "lathe operator", "grinder operator",
    "maintenance technician", "maintenance mechanic",
    "industrial maintenance", "millwright",
    "plant manager", "production supervisor", "shift supervisor",
    "production planner", "production scheduler",
    "supply chain manager", "supply chain analyst",
    "inventory control specialist", "inventory manager",
    "warehouse associate", "warehouse worker", "warehouse supervisor",
    "warehouse manager", "warehouse coordinator",
    "purchasing agent", "purchasing manager", "buyer",
    "logistics coordinator", "logistics manager",
    "forklift certified", "order picker", "reach truck driver",
    "shipping coordinator", "receiving coordinator",
    "fabrication technician", "fabrication worker",
    "welding fabricator", "sheet metal fabricator",
    "assembler", "mechanical assembler", "electrical assembler",
    "prototype technician", "R&D technician",
    "test technician", "test engineer manufacturing",
    "engineering technician", "process technician",
    "chemical operator", "batch mixer", "compounder",
    "injection molding operator", "blow molding operator",
    "extrusion operator", "thermoform operator",
    "printer operator", "offset printer", "digital printer",
    "label maker", "screen printer",
]

OFFICE_ADMIN_KEYWORDS = [
    "office manager", "office administrator", "office coordinator",
    "office assistant", "office clerk", "office specialist",
    "receptionist", "front desk receptionist", "front desk associate",
    "front desk coordinator", "greeter", "switchboard operator",
    "administrative assistant", "admin assistant", "executive assistant",
    "senior executive assistant", "EA to CEO", "administrative coordinator",
    "administrative specialist", "administrative associate",
    "legal secretary", "paralegal", "legal assistant",
    "legal clerk", "court reporter", "court clerk",
    "law clerk", "legal researcher", "legal analyst",
    "bookkeeper", "accounts payable clerk", "accounts receivable clerk",
    "billing specialist", "billing clerk", "billing coordinator",
    "accountant", "senior accountant", "staff accountant",
    "accounts payable specialist", "accounts receivable specialist",
    "payroll specialist", "payroll clerk", "payroll administrator",
    "financial analyst", "senior financial analyst",
    "FP&A analyst", "budget analyst", "cost accountant",
    "tax accountant", "tax preparer", "tax analyst",
    "HR manager", "human resources manager", "HR director",
    "HR generalist", "HR specialist", "HR coordinator",
    "HR business partner", "HRBP", "HR administrator",
    "recruiter", "talent acquisition specialist", "talent acquisition manager",
    "sourcer", "technical recruiter", "campus recruiter",
    "staffing coordinator", "staffing specialist",
    "training coordinator", "training manager", "L&D specialist",
    "learning and development", "training specialist",
    "benefits administrator", "benefits coordinator",
    "compensation analyst", "compensation specialist",
    "employee relations specialist", "employee relations manager",
    "project manager", "senior project manager",
    "program manager", "portfolio manager",
    "business analyst", "senior business analyst",
    "systems analyst", "process analyst",
    "operations manager", "operations coordinator",
    "operations analyst", "operations director",
    "quality assurance specialist", "quality specialist",
    "compliance officer", "compliance analyst", "compliance manager",
    "regulatory analyst", "regulatory specialist",
    "procurement specialist", "procurement manager",
    "contract administrator", "contract specialist",
    "document control specialist", "records manager",
    "data entry clerk", "data entry operator", "data entry specialist",
    "filing clerk", "file clerk", "records clerk",
    "mail clerk", "mail room attendant", "courier",
    "dispatch clerk", "scheduling coordinator",
    "meeting planner", "event planner", "event coordinator",
]

SALES_KEYWORDS = [
    "sales representative", "sales associate", "sales consultant",
    "sales executive", "inside sales", "outside sales",
    "field sales representative", "door to door sales",
    "retail sales associate", "retail sales consultant",
    "sales manager", "sales director", "VP of sales",
    "regional sales manager", "district sales manager",
    "territory sales manager", "area sales manager",
    "account executive", "senior account executive",
    "account manager", "senior account manager",
    "key account manager", "enterprise account executive",
    "strategic account manager", "client manager",
    "business development representative", "BDR",
    "sales development representative", "SDR",
    "lead generator", "appointment setter",
    "telemarketer", "telesales representative",
    "call center sales", "inbound sales", "outbound sales",
    "retail manager", "store manager", "assistant store manager",
    "assistant manager retail", "shift manager",
    "merchandiser", "visual merchandiser", "stock associate",
    "cashier", "checkout associate", "customer service associate",
    "showroom associate", "counter sales",
    "auto sales", "car salesperson", "automotive sales",
    "real estate sales", "real estate agent", "real estate broker",
    "insurance sales", "insurance agent", "insurance broker",
    "financial services sales", "wealth management advisor",
    "medical device sales", "pharmaceutical sales rep",
    "SaaS sales", "software sales", "technology sales",
]

MARKETING_KEYWORDS = [
    "marketing manager", "marketing director", "VP of marketing",
    "marketing coordinator", "marketing specialist", "marketing associate",
    "digital marketing specialist", "digital marketing manager",
    "digital marketing coordinator", "digital marketing analyst",
    "SEO specialist", "SEO manager", "SEO analyst",
    "SEM specialist", "PPC specialist", "paid media specialist",
    "social media manager", "social media specialist", "social media coordinator",
    "social media analyst", "community manager",
    "content writer", "content creator", "content strategist",
    "content marketing manager", "content specialist",
    "copywriter", "senior copywriter", "creative copywriter",
    "blog writer", "technical writer content",
    "email marketing specialist", "email marketing manager",
    "email campaign specialist", "marketing automation specialist",
    "marketing operations", "marketing analytics",
    "brand manager", "senior brand manager",
    "brand strategist", "brand designer",
    "product marketing manager", "product marketing specialist",
    "public relations specialist", "PR manager",
    "communications specialist", "communications manager",
    "media buyer", "media planner", "media strategist",
    "graphic designer marketing", "creative designer",
    "art director", "creative director",
    "video producer", "video content creator",
    "influencer marketing manager", "affiliate marketing manager",
    "growth hacker", "growth marketing manager",
    "demand generation manager", "demand generation specialist",
    "marketing data analyst", "marketing technologist",
    "CRM specialist", "HubSpot specialist", "Salesforce marketer",
]

CUSTOMER_SERVICE_KEYWORDS = [
    "customer service representative", "customer service agent",
    "customer service specialist", "customer service associate",
    "customer support representative", "customer support specialist",
    "customer support agent", "customer success manager",
    "customer success specialist", "client success manager",
    "call center representative", "call center agent", "call center associate",
    "inbound call center", "outbound call center",
    "contact center agent", "contact center specialist",
    "help desk technician", "help desk specialist", "help desk analyst",
    "technical support specialist", "technical support representative",
    "IT help desk", "IT support specialist",
    "chat support agent", "chat support specialist",
    "email support specialist", "ticket support specialist",
    "service desk analyst", "service desk specialist",
    "client services coordinator", "client services manager",
    "client relationship manager", "account support specialist",
    "order processing specialist", "order entry specialist",
    "complaint resolution specialist", "escalation specialist",
    "quality assurance customer service", "CSAT specialist",
    "multilingual customer service", "bilingual customer service",
]

HOSPITALITY_KEYWORDS = [
    "hotel front desk", "front desk agent", "front desk clerk",
    "hotel receptionist", "night auditor", "front office manager",
    "hotel manager", "assistant hotel manager", "hotel general manager",
    "housekeeping supervisor", "housekeeping manager", "housekeeper",
    "room attendant", "laundry attendant", "linen attendant",
    "concierge", "bellhop", "doorman", "valet",
    "chef", "executive chef", "sous chef",
    "line cook", "prep cook", "short order cook",
    "kitchen manager", "kitchen supervisor", "kitchen helper",
    "pastry chef", "baker", "bakery assistant",
    "bartender", "barback", "mixologist",
    "server", "waiter", "waitress", "food runner",
    "busser", "busboy", "dining room attendant",
    "restaurant manager", "assistant restaurant manager",
    "restaurant supervisor", "shift manager restaurant",
    "catering coordinator", "catering manager",
    "food service worker", "food service associate",
    "cafeteria worker", "cafeteria manager",
    "dishwasher", "kitchen porter", "scullery",
    "food and beverage manager", "F&B manager",
    "banquet manager", "banquet captain",
    "sommelier", "wine steward",
    "gaming dealer", "casino dealer", "poker dealer",
    "spa manager", "spa therapist", "esthetician",
]

TRANSPORTATION_KEYWORDS = [
    "truck driver", "CDL driver", "CDL A driver", "CDL B driver",
    "long haul truck driver", "short haul driver", "local driver",
    "delivery driver", "package delivery driver",
    "Amazon delivery driver", "FedEx driver", "UPS driver",
    "DHL driver", "courier driver", "last mile delivery",
    "bus driver", "school bus driver", "transit bus driver",
    "shuttle driver", "coach driver",
    "taxi driver", "cab driver", "rideshare driver",
    "Uber driver", "Lyft driver",
    "forklift driver", "reach truck driver",
    "dump truck driver", "cement truck driver",
    "tow truck driver", "flatbed driver",
    "tanker driver", "hazmat driver", "hazmat tanker",
    "reefer driver", "refrigerated truck driver",
    "flatbed truck driver", "lowboy driver",
    "car hauler", "auto transport driver",
    "moving company driver", "mover", "furniture mover",
    "dispatch coordinator", "dispatcher",
    "fleet manager", "fleet coordinator", "fleet maintenance",
    "routing specialist", "route planner", "route driver",
    "supply chain coordinator", "logistics coordinator",
    "logistics manager", "freight broker", "freight agent",
    "customs broker", "import export specialist",
    "warehouse coordinator", "shipping coordinator",
    "mail carrier", "postal worker", "postal carrier",
    "package handler", "sorter", "unload loader",
    "ramp agent", "ground crew", "line service technician",
    "baggage handler", "ramp worker",
]

EDUCATION_KEYWORDS = [
    "teacher", "classroom teacher", "certified teacher",
    "elementary teacher", "middle school teacher", "high school teacher",
    "teacher assistant", "teacher aide", "paraprofessional",
    "substitute teacher", "long term substitute",
    "tutor", "academic tutor", "online tutor",
    "school counselor", "guidance counselor",
    "school social worker", "school psychologist",
    "librarian", "school librarian", "media specialist",
    "library assistant", "library technician",
    "special education teacher", "SPED teacher",
    "inclusion teacher", "resource teacher",
    "preschool teacher", "pre-K teacher", "early childhood teacher",
    "daycare worker", "daycare teacher", "child care worker",
    "childcare provider", "child care director",
    "campus security", "school resource officer",
    "custodian", "janitor", "school custodian",
    "school bus driver", "bus monitor",
    "college professor", "adjunct professor", "lecturer",
    "teaching assistant", "graduate assistant", "research assistant",
    "academic advisor", "academic coordinator",
    "registrar", "registrar assistant",
    "admissions counselor", "admissions representative",
    "financial aid counselor", "bursar",
    "dean", "department chair", "provost",
    "curriculum developer", "instructional designer",
    "test proctor", "exam administrator",
]

GOVERNMENT_KEYWORDS = [
    "police officer", "patrol officer", "law enforcement officer",
    "detective", "investigator", "criminal investigator",
    "sheriff", "deputy sheriff", "bailiff",
    "state trooper", "highway patrol", "park police",
    "police sergeant", "police lieutenant", "police captain",
    "firefighter", "fire fighter", "fire engineer",
    "fire captain", "fire chief", "fire inspector",
    "arson investigator", "fire investigator",
    "corrections officer", "correctional officer",
    "prison guard", "jail officer", "detention officer",
    "security guard", "security officer", "armed security",
    "unarmed security", "security patrol",
    "private investigator", "PI", "loss prevention",
    "dispatcher", "911 dispatcher", "911 operator",
    "emergency dispatcher", "police dispatcher",
    "court clerk", "court officer", "court bailiff",
    "probation officer", "parole officer",
    "pretrial services officer",
    "social worker", "case manager", "child protective services",
    "public health inspector", "health inspector",
    "food inspector", "building inspector",
    "code enforcement officer", "housing inspector",
    "fire inspector", "fire marshal",
    "park ranger", "forest ranger", "game warden",
    "conservation officer", "wildlife officer",
    "customs officer", "border patrol agent",
    "immigration officer", "ICE agent",
    "postal inspector", "municipal clerk",
    "zoning administrator", "planning technician",
    "election official", "poll worker",
    "military", "armed forces", "national guard",
]

FINANCE_KEYWORDS = [
    "bank teller", "teller", "personal banker",
    "bank manager", "branch manager bank", "assistant branch manager",
    "loan officer", "loan processor", "mortgage loan officer",
    "mortgage processor", "mortgage underwriter",
    "financial advisor", "financial planner",
    "wealth manager", "wealth management advisor",
    "investment advisor", "investment banker",
    "portfolio manager", "fund manager",
    "trading analyst", "trader", "equity analyst",
    "research analyst", "equity research analyst",
    "credit analyst", "credit manager", "credit officer",
    "underwriter", "insurance underwriter", "loan underwriter",
    "claims adjuster", "claims examiner", "claims specialist",
    "insurance agent", "insurance broker", "insurance representative",
    "actuary", "actuarial analyst",
    "auditor", "internal auditor", "external auditor",
    "senior auditor", "IT auditor",
    "tax preparer", "tax accountant", "tax consultant",
    "CPA", "certified public accountant",
    "budget analyst", "cost analyst", "cost accountant",
    "forensic accountant", "forensic auditor",
    "compliance officer banking", "regulatory compliance analyst",
    "anti-money laundering analyst", "AML analyst",
    "KYC analyst", "due diligence analyst",
    "treasury analyst", "treasury manager",
    "accounts receivable manager", "accounts payable manager",
    "revenue cycle manager", "revenue analyst",
    "risk analyst", "risk manager", "risk officer",
    "operations analyst banking", "branch operations",
]

AVIATION_KEYWORDS = [
    "pilot", "commercial pilot", "airline pilot",
    "private pilot", "flight instructor",
    "copilot", "first officer", "captain pilot",
    "flight attendant", "cabin crew", "purser",
    "aircraft mechanic", "A&P mechanic", "aviation maintenance technician",
    "aircraft technician", "avionics technician",
    "air traffic controller", "ATC",
    "ramp agent", "ground crew", "ground handling",
    "baggage handler", "cabin cleaner",
    "airline customer service", "airline agent",
    "gate agent", "ticketing agent",
    "flight dispatcher", "flight planner",
    "aircraft fueler", "deicing technician",
    "airport operations", "airport security",
    "TSA officer", "TSA agent",
]

ENERGY_KEYWORDS = [
    "power plant operator", "power plant technician",
    "utility worker", "utility lineman",
    "electrical lineman", "power line installer",
    "substation technician", "relay technician",
    "oil field worker", "roughneck", "derrickhand",
    "drilling engineer", "drilling technician",
    "refinery operator", "process operator refinery",
    "pipeline operator", "pipeline technician",
    "nuclear technician", "nuclear operator",
    "solar panel installer", "solar technician", "solar electrician",
    "wind turbine technician", "wind farm technician",
    "water treatment operator", "wastewater treatment operator",
    "water plant operator", "water system operator",
    "gas utility technician", "natural gas technician",
    "meter reader", "utility locator",
    "energy auditor", "energy consultant",
    "building automation technician", "BAS technician",
    "HVAC controls technician", "BMS operator",
]

AGRICULTURE_KEYWORDS = [
    "farm worker", "farm laborer", "farm hand",
    "ranch hand", "ranch worker",
    "agricultural technician", "agricultural worker",
    "irrigation specialist", "irrigation technician",
    "pest management specialist", "pest control agriculture",
    "horticulturist", "greenhouse worker", "nursery worker",
    "livestock handler", "livestock worker",
    "dairy worker", "dairy farm hand",
    "poultry worker", "poultry farm worker",
    "harvest worker", "crop worker", "field worker",
    "equipment operator farm", "tractor operator",
    "agricultural equipment mechanic",
    "beekeeper", "apiculturist",
    "florist", "flower shop worker",
    "landscaping foreman", "landscape architect",
    "arborist certified", "urban forester",
]

MARITIME_KEYWORDS = [
    "merchant marine", "deckhand", "able seaman",
    "boat captain", "ship captain", "barge captain",
    "marine engineer", "ship engineer",
    "longshoreman", "dock worker", "stevedore",
    "harbor pilot", "towboat pilot",
    "merchant mariner", "unlicensed deckhand",
    "marine electrician", "marine mechanic",
]

CREATIVE_KEYWORDS = [
    "videographer", "video producer", "video editor",
    "photographer", "photo editor",
    "editor", "copy editor", "proofreader",
    "journalist", "reporter", "news anchor",
    "news producer", "broadcast journalist",
    "animator", "2D animator", "3D animator",
    "motion graphics designer", "VFX artist",
    "illustrator", "concept artist",
    "character designer", "storyboard artist",
    "game designer", "level designer",
    "sound engineer", "audio engineer",
    "music producer", "music teacher",
    "lighting technician", "lighting designer",
    "stagehand", "stage manager",
    "event coordinator", "event planner",
    "wedding planner", "wedding coordinator",
    "interior designer", "interior decorator",
    "architect", "landscape architect",
    "industrial designer", "product designer",
]

CLEANING_KEYWORDS = [
    "janitor", "custodian", "building custodian",
    "housekeeper", "hotel housekeeper",
    "commercial cleaner", "industrial cleaner",
    "office cleaner", "cleaning crew",
    "window washer", "window cleaning technician",
    "carpet cleaner", "carpet cleaning technician",
    "floor care specialist", "floor technician",
    "pressure washer", "power washing technician",
    "biohazard cleaner", "crime scene cleaner",
    "medical facility cleaner", "healthcare cleaner",
    "post construction cleanup", "construction cleaner",
    "move out cleaning", "deep cleaning specialist",
]

VETERINARY_KEYWORDS = [
    "veterinarian", "veterinary surgeon",
    "veterinary technician", "vet tech",
    "veterinary assistant", "animal care specialist",
    "kennel technician", "kennel attendant",
    "dog groomer", "pet groomer",
    "dog trainer", "pet trainer", "animal trainer",
    "pet sitter", "dog walker",
    "pet care associate", "animal shelter worker",
    "zoo keeper", "wildlife rehabilitator",
    "animal control officer",
]

WELDING_SKILLED_KEYWORDS = [
    "pipe welder", "structural welder",
    "underwater welder", "nuclear welder",
    "boilermaker", "boiler maker",
    "ironworker", "structural ironworker",
    "reinforcing ironworker", "ornamental ironworker",
    "sheet metal worker", "sheet metal installer",
    "insulation worker", "mechanical insulation",
    "asbestos worker", "hazardous materials worker",
    "scaffolding erector", "scaffold builder",
    "rigger", "signalperson", "crane rigger",
]

SAFETY_KEYWORDS = [
    "safety officer", "safety manager", "safety coordinator",
    "safety director", "EHS manager", "EHS specialist",
    "environmental health safety", "occupational health specialist",
    "safety inspector", "fire safety officer",
    "safety trainer", "safety consultant",
    "OSHA compliance officer", "risk safety officer",
]

NURSING_KEYWORDS = [
    "travel nurse", "travel nursing", "agency nurse",
    "per diem nurse", "float pool nurse",
    "ICU nurse", "ER nurse", "emergency room nurse",
    "OR nurse", "operating room nurse",
    "pediatric nurse", "NICU nurse",
    "oncology nurse", "cardiac nurse",
    "labor and delivery nurse", "L&D nurse",
    "postpartum nurse", "ante partum nurse",
    "psychiatric nurse", "mental health nurse",
    "geriatric nurse", "gerontology nurse",
    "school nurse", "occupational health nurse",
    "nurse educator", "nurse case manager",
    "nurse informaticist", "nurse anesthetist",
    "clinical nurse leader", "charge nurse",
]

DENTAL_KEYWORDS = [
    "dentist", "dental surgeon", "orthodontist",
    "dental hygienist", "registered dental hygienist",
    "dental assistant", "certified dental assistant",
    "dental office manager", "dental receptionist",
    "dental lab technician", "dental ceramist",
    "dental billing specialist",
]

OPTOMETRY_KEYWORDS = [
    "optometrist", "optician", "optical manager",
    "ophthalmic technician", "ophthalmic assistant",
    "optical lab technician", "lens technician",
]

EMS_KEYWORDS = [
    "EMT", "paramedic", "EMT-Basic", "EMT-Paramedic",
    "emergency medical technician", "firefighter EMT",
    "ambulance driver", "EMS supervisor",
    "EMS instructor", "EMS coordinator",
    "flight paramedic", "critical care paramedic",
]

MILITARY_TRANSITION_KEYWORDS = [
    "veteran", "military veteran", "veteran transition",
    "military to civilian", "veteran employment",
    "transitioning service member",
]

# All keywords combined
ALL_KEYWORDS = list(dict.fromkeys(  # dedup while preserving order
    TECH_KEYWORDS + HEALTHCARE_KEYWORDS + BLUE_COLLAR_KEYWORDS +
    MANUFACTURING_KEYWORDS + OFFICE_ADMIN_KEYWORDS + SALES_KEYWORDS +
    MARKETING_KEYWORDS + CUSTOMER_SERVICE_KEYWORDS + HOSPITALITY_KEYWORDS +
    TRANSPORTATION_KEYWORDS + EDUCATION_KEYWORDS + GOVERNMENT_KEYWORDS +
    FINANCE_KEYWORDS + AVIATION_KEYWORDS + ENERGY_KEYWORDS +
    AGRICULTURE_KEYWORDS + MARITIME_KEYWORDS + CREATIVE_KEYWORDS +
    CLEANING_KEYWORDS + VETERINARY_KEYWORDS + WELDING_SKILLED_KEYWORDS +
    SAFETY_KEYWORDS + NURSING_KEYWORDS + DENTAL_KEYWORDS +
    OPTOMETRY_KEYWORDS + EMS_KEYWORDS + MILITARY_TRANSITION_KEYWORDS
))

# All locations
ALL_LOCATIONS = list(dict.fromkeys([
    # US Major Cities
    "Remote", "New York", "San Francisco", "Austin", "Los Angeles",
    "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio",
    "San Diego", "Dallas", "San Jose", "Jacksonville",
    "Fort Worth", "Columbus", "Charlotte", "Indianapolis",
    "Seattle", "Denver", "Boston", "Nashville", "Portland",
    "Las Vegas", "Atlanta", "Miami", "Minneapolis", "Tampa",
    "Detroit", "Orlando", "Pittsburgh", "Sacramento",
    "Cincinnati", "Kansas City", "Cleveland", "Newark",
    "Milwaukee", "Omaha", "Raleigh", "Memphis", "Louisville",
    "Richmond", "Salt Lake City", "Hartford", "Buffalo",
    "Birmingham", "Rochester", "Tulsa", "Oklahoma City",
    "Grand Rapids", "Honolulu", "St Louis", "Albuquerque",
    "Tucson", "Fresno", "Sacramento", "Mesa", "Kansas City",
    "Colorado Springs", "Omaha", "Raleigh", "Long Beach",
    "Virginia Beach", "Miami Beach", "Oakland", "Minneapolis",
    "Tulsa", "Tampa", "Arlington", "New Orleans", "Wichita",
    # US Mid-size
    "Boise", "Provo", "Salt Lake City", "Spokane", "Boise Idaho",
    "Scottsdale", "Chandler", "Glendale", "Gilbert", "Tempe",
    "Plano", "Irving", "Arlington TX", "Frisco", "McKinney",
    "Madison", "Des Moines", "Lincoln", "Sioux Falls",
    "Fargo", "Bismarck", "Billings", "Missoula",
    "Anchorage", "Fairbanks", "Juneau",
    "Burlington VT", "Portland ME", "Concord NH",
    # UK
    "London", "Manchester", "Birmingham", "Edinburgh", "Glasgow",
    "Leeds", "Liverpool", "Bristol", "Sheffield", "Nottingham",
    "Newcastle", "Leicester", "Coventry", "Bradford", "Cardiff",
    "Belfast", "Aberdeen", "Oxford", "Cambridge", "Brighton",
    "Reading", "Southampton", "Derby", "Exeter", "Norwich",
    # Canada
    "Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa",
    "Edmonton", "Winnipeg", "Quebec City", "Hamilton", "Kitchener",
    "Halifax", "Victoria", "Saskatoon", "Regina", "London Ontario",
    "St John", "Fredericton", "Kelowna", "Barrie", "Guelph",
    # India
    "Bangalore", "Bengaluru", "Mumbai", "Delhi", "Hyderabad",
    "Pune", "Chennai", "Noida", "Gurgaon", "Gurugram",
    "Ahmedabad", "Jaipur", "Kolkata", "Coimbatore", "Kochi",
    "Indore", "Bhopal", "Lucknow", "Chandigarh", "Nagpur",
    "Thiruvananthapuram", "Visakhapatnam", "Patna", "Vadodara",
    "Surat", "Rajkot", "Madurai", "Mysore", "Jodhpur",
    "Amritsar", "Dehradun", "Goa", "Ranchi", "Bhubaneswar",
    "Guwahati", "Agra", "Varanasi", "Meerut", "Faridabad",
    "Navi Mumbai", "Thane", "Andheri", "Borivali", "Powai",
    "Whitefield", "Electronic City", "Koramangala", "HSR Layout",
    "JP Nagar", "BTM Layout", "Indiranagar", "MG Road Bangalore",
    # Southeast Asia
    "Singapore", "Kuala Lumpur", "Jakarta", "Bangkok", "Ho Chi Minh City",
    "Manila", "Hanoi", "Phnom Penh", "Yangon",
    # Middle East
    "Dubai", "Abu Dhabi", "Sharjah", "Doha", "Riyadh", "Jeddah",
    "Muscat", "Bahrain", "Kuwait City",
    # Europe
    "Berlin", "Munich", "Frankfurt", "Hamburg", "Cologne",
    "Amsterdam", "Rotterdam", "The Hague", "Eindhoven",
    "Paris", "Lyon", "Marseille", "Toulouse", "Nice",
    "Dublin", "Cork", "Galway",
    "Barcelona", "Madrid", "Valencia", "Seville", "Bilbao",
    "Rome", "Milan", "Turin", "Naples", "Florence",
    "Stockholm", "Gothenburg", "Malmo",
    "Copenhagen", "Aarhus",
    "Oslo", "Bergen",
    "Helsinki",
    "Vienna", "Zurich", "Geneva", "Basel",
    "Warsaw", "Krakow", "Wroclaw", "Gdansk",
    "Prague", "Brno",
    "Budapest",
    "Lisbon", "Porto",
    "Athens", "Thessaloniki",
    # Australia / New Zealand
    "Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide",
    "Gold Coast", "Canberra", "Newcastle AU", "Wollongong",
    "Auckland", "Wellington", "Christchurch", "Hamilton NZ",
    # Africa
    "Cape Town", "Johannesburg", "Durban", "Pretoria",
    "Nairobi", "Lagos", "Accra", "Cairo",
    # South America
    "Sao Paulo", "Rio de Janeiro", "Buenos Aires", "Bogota",
    "Lima", "Santiago", "Medellin",
    # East Asia
    "Tokyo", "Osaka", "Seoul", "Busan", "Taipei",
    "Hong Kong", "Shanghai", "Beijing", "Shenzhen",
]))

# Stats
print(f"Total keywords: {len(ALL_KEYWORDS)}")
print(f"Total locations: {len(ALL_LOCATIONS)}")
