#!/usr/bin/env python3
"""PDF Export — Generate clean PDF reports of leads and job data.

Usage:
    python -m scripts.pdf_export --leads --output leads_report.pdf
    python -m scripts.pdf_export --jobs --keyword "python" --limit 50
    python -m scripts.pdf_export --analytics
"""
from __future__ import annotations
import json, os, sqlite3, time
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB = ROOT / "jobs.db"
OUTPUT_DIR = ROOT / "exports"


def get_db():
    return sqlite3.connect(str(DB), timeout=10)


def ensure_output_dir():
    OUTPUT_DIR.mkdir(exist_ok=True)


def generate_html_report(title, sections):
    """Generate an HTML report."""
    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{title}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 40px; color: #1f2937; }}
        h1 {{ color: #1e40af; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; }}
        h2 {{ color: #374151; margin-top: 30px; }}
        table {{ border-collapse: collapse; width: 100%; margin: 15px 0; }}
        th, td {{ border: 1px solid #d1d5db; padding: 8px 12px; text-align: left; font-size: 13px; }}
        th {{ background: #f3f4f6; font-weight: 600; }}
        tr:nth-child(even) {{ background: #f9fafb; }}
        .badge {{ display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; }}
        .badge-high {{ background: #dcfce7; color: #166534; }}
        .badge-mid {{ background: #fef9c3; color: #854d0e; }}
        .badge-low {{ background: #fee2e2; color: #991b1b; }}
        .stat {{ display: inline-block; margin: 10px 20px; padding: 15px; background: #f3f4f6; border-radius: 8px; }}
        .stat .value {{ font-size: 24px; font-weight: bold; color: #1e40af; }}
        .stat .label {{ font-size: 12px; color: #6b7280; }}
        .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #d1d5db; color: #9ca3af; font-size: 11px; }}
        a {{ color: #2563eb; text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    <p style="color: #6b7280;">Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}</p>
"""
    for section in sections:
        html += section
    html += """
    <div class="footer">
        <p>Generated by LeadFlow Job Scraper | <a href="http://localhost:8000">View Live Dashboard</a></p>
    </div>
</body>
</html>"""
    return html


def generate_leads_report(limit=50, output=None):
    """Generate a leads report."""
    conn = get_db()
    conn.row_factory = sqlite3.Row

    jobs = conn.execute(
        "SELECT title, company, location, url, source, salary, posted_at, first_seen_at, tags "
        "FROM jobs WHERE is_active = 1 ORDER BY first_seen_at DESC LIMIT ?",
        (limit,)
    ).fetchall()

    conn.close()

    sections = []
    sections.append(f"<h2>📋 Top {limit} Leads</h2>")
    sections.append("<table><tr><th>#</th><th>Title</th><th>Company</th><th>Location</th><th>Source</th><th>Posted</th></tr>")

    for i, job in enumerate(jobs, 1):
        sections.append(
            f"<tr><td>{i}</td>"
            f"<td><a href='{job['url']}' target='_blank'>{job['title']}</a></td>"
            f"<td>{job['company'] or '-'}</td>"
            f"<td>{job['location'] or '-'}</td>"
            f"<td><span class='badge badge-mid'>{job['source'] or '-'}</span></td>"
            f"<td>{job['posted_at'][:10] if job['posted_at'] else '-'}</td></tr>"
        )

    sections.append("</table>")

    ensure_output_dir()
    output = output or str(OUTPUT_DIR / f"leads_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html")
    with open(output, 'w', encoding='utf-8') as f:
        f.write(generate_html_report("LeadFlow Leads Report", sections))

    print(f"Report saved to: {output}")
    return output


def generate_jobs_report(keyword="", location="", limit=50, output=None):
    """Generate a job search report."""
    conn = get_db()
    conn.row_factory = sqlite3.Row

    conditions = ["is_active = 1"]
    params = []

    if keyword:
        conditions.append("(title LIKE ? OR company LIKE ? OR description LIKE ?)")
        like = f"%{keyword}%"
        params.extend([like, like, like])

    if location:
        conditions.append("LOWER(location) LIKE ?")
        params.append(f"%{location.lower()}%")

    params.append(limit)

    jobs = conn.execute(
        f"SELECT title, company, location, url, source, salary, posted_at, description "
        f"FROM jobs WHERE {' AND '.join(conditions)} "
        f"ORDER BY first_seen_at DESC LIMIT ?",
        params
    ).fetchall()

    total = conn.execute(
        f"SELECT COUNT(*) FROM jobs WHERE {' AND '.join(conditions)}",
        params[:-1]
    ).fetchone()[0]

    conn.close()

    sections = []

    # Summary
    sections.append("<h2>📊 Summary</h2>")
    sections.append(f"""
    <div>
        <div class="stat"><div class="value">{total}</div><div class="label">Total Jobs</div></div>
        <div class="stat"><div class="value">{keyword or 'All'}</div><div class="label">Keyword</div></div>
        <div class="stat"><div class="value">{location or 'All'}</div><div class="label">Location</div></div>
        <div class="stat"><div class="value">{limit}</div><div class="label">Showing</div></div>
    </div>
    """)

    # Jobs table
    sections.append(f"<h2>💼 Jobs (Showing {min(limit, len(jobs))} of {total})</h2>")
    sections.append("<table><tr><th>#</th><th>Title</th><th>Company</th><th>Location</th><th>Source</th><th>Posted</th></tr>")

    for i, job in enumerate(jobs, 1):
        sections.append(
            f"<tr><td>{i}</td>"
            f"<td><a href='{job['url']}' target='_blank'>{job['title']}</a></td>"
            f"<td>{job['company'] or '-'}</td>"
            f"<td>{job['location'] or '-'}</td>"
            f"<td>{job['source'] or '-'}</td>"
            f"<td>{job['posted_at'][:10] if job['posted_at'] else '-'}</td></tr>"
        )

    sections.append("</table>")

    ensure_output_dir()
    output = output or str(OUTPUT_DIR / f"jobs_{keyword or 'all'}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html")
    with open(output, 'w', encoding='utf-8') as f:
        f.write(generate_html_report(f"Job Report: {keyword or 'All'} in {location or 'All'}", sections))

    print(f"Report saved to: {output}")
    return output


def generate_analytics_report(output=None):
    """Generate an analytics dashboard report."""
    conn = get_db()

    # Basic stats
    total = conn.execute("SELECT COUNT(*) FROM jobs WHERE is_active = 1").fetchone()[0]
    companies = conn.execute("SELECT COUNT(DISTINCT LOWER(TRIM(company))) FROM jobs WHERE company != '' AND is_active = 1").fetchone()[0]
    sources = conn.execute("SELECT source, COUNT(*) FROM jobs WHERE is_active = 1 GROUP BY source ORDER BY COUNT(*) DESC LIMIT 10").fetchall()

    # Recent activity
    recent = conn.execute(
        "SELECT date(first_seen_at) as day, COUNT(*) FROM jobs "
        "WHERE is_active = 1 AND first_seen_at >= date('now', '-7 days') "
        "GROUP BY day ORDER BY day"
    ).fetchall()

    conn.close()

    sections = []

    # Summary stats
    sections.append("<h2>📊 Overview</h2>")
    sections.append(f"""
    <div>
        <div class="stat"><div class="value">{total:,}</div><div class="label">Total Jobs</div></div>
        <div class="stat"><div class="value">{companies:,}</div><div class="label">Companies</div></div>
        <div class="stat"><div class="value">{len(sources)}</div><div class="label">Active Sources</div></div>
        <div class="stat"><div class="value">{sum(r[1] for r in recent)}</div><div class="label">Last 7 Days</div></div>
    </div>
    """)

    # Sources breakdown
    sections.append("<h2>📡 Top Sources</h2>")
    sections.append("<table><tr><th>Source</th><th>Count</th><th>%</th></tr>")
    for source, count in sources:
        pct = round(count / total * 100, 1) if total else 0
        sections.append(f"<tr><td>{source}</td><td>{count:,}</td><td>{pct}%</td></tr>")
    sections.append("</table>")

    # Recent activity
    sections.append("<h2>📈 Last 7 Days</h2>")
    sections.append("<table><tr><th>Date</th><th>New Jobs</th></tr>")
    for day, count in recent:
        sections.append(f"<tr><td>{day}</td><td>{count:,}</td></tr>")
    sections.append("</table>")

    ensure_output_dir()
    output = output or str(OUTPUT_DIR / f"analytics_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html")
    with open(output, 'w', encoding='utf-8') as f:
        f.write(generate_html_report("LeadFlow Analytics Dashboard", sections))

    print(f"Report saved to: {output}")
    return output


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--leads", action="store_true", help="Generate leads report")
    parser.add_argument("--jobs", action="store_true", help="Generate jobs report")
    parser.add_argument("--analytics", action="store_true", help="Generate analytics report")
    parser.add_argument("--keyword", default="")
    parser.add_argument("--location", default="")
    parser.add_argument("--limit", type=int, default=50)
    parser.add_argument("--output", default=None)
    args = parser.parse_args()

    if args.leads:
        generate_leads_report(args.limit, args.output)
    elif args.jobs:
        generate_jobs_report(args.keyword, args.location, args.limit, args.output)
    elif args.analytics:
        generate_analytics_report(args.output)
    else:
        print("Use --leads, --jobs, or --analytics to generate a report")


if __name__ == "__main__":
    main()
